export const DIRECTORY_DESCRIPTIONS: Record<string, { zh: string; en: string }> = {
  "arxiv-abs": { zh: "官方摘要与版本信息", en: "Official abstract and versions" },
  "arxiv-pdf": { zh: "官方论文 PDF", en: "Official paper PDF" },
  "arxiv-html": { zh: "官方 HTML 阅读", en: "Official HTML reader" },
  "arxiv-txt": { zh: "论文摘要与纯文本", en: "Abstracts and plain text" },
  arxiv2md: { zh: "论文转 Markdown", en: "Papers to Markdown" },
  "arxiv-src": { zh: "论文 TeX 源码", en: "Paper TeX source" },
  alphaxiv: { zh: "论文阅读与社区注释", en: "Reading and community notes" },
  "papers-cool": { zh: "Kimi 辅助论文阅读", en: "Kimi-assisted paper reading" },
  hjfy: { zh: "同版式中文译文", en: "Layout-preserving Chinese translation" },
  chinarxiv: { zh: "论文中英双语翻译", en: "Bilingual paper translation" },
  chatpaper: { zh: "每日论文与 AI 对话", en: "Daily papers and AI chat" },
  iarxiv: { zh: "论文发现，需登录", en: "Paper discovery; sign-in required" },
  arxivdaily: { zh: "每日论文与中文摘要", en: "Daily papers and Chinese summaries" },
  paperdance: { zh: "图文速览论文", en: "Visual paper highlights" },
  arxivtldr: { zh: "论文要点速览", en: "Concise paper summaries" },
  arxivxplorer: { zh: "arXiv 语义搜索", en: "Semantic arXiv search" },
  "arxiv-bshk": { zh: "浏览器内语义搜索", en: "In-browser semantic search" },
  scirate: { zh: "论文评分与讨论", en: "Paper ratings and discussion" },
  arxivisual: { zh: "论文可视化讲解", en: "Visual paper explanations" },
  "hf-papers": { zh: "论文讨论与模型资源", en: "Paper discussion and model resources" },
  ar5iv: { zh: "论文 HTML 阅读", en: "HTML paper reader" },
  "emergent-mind": { zh: "AI 摘要与研究追踪", en: "AI summaries and research tracking" },
  talk2arxiv: { zh: "论文智能问答", en: "AI paper Q&A" },
  sciencecast: { zh: "科研论文视频讲解", en: "Research paper videos" },
  explainpaper: { zh: "论文难句解释", en: "Explain difficult passages" },
  scispace: { zh: "论文检索与 AI 阅读", en: "Paper search and AI reading" },
  chatdoc: { zh: "带引用的文档问答", en: "Document Q&A with citations" },
  consensus: { zh: "基于论文证据的问答", en: "Evidence-based research answers" },
  litmaps: { zh: "引文地图与文献发现", en: "Citation maps and discovery" },
  "connected-papers": { zh: "相似论文关系图", en: "Related-paper graphs" },
  inciteful: { zh: "论文引文网络探索", en: "Explore citation networks" },
  paperscape: { zh: "arXiv 论文地图", en: "Map of arXiv research" },
  papermatch: { zh: "查找相似论文", en: "Find similar papers" },
  "semantic-scholar": { zh: "学术检索与引用分析", en: "Scholarly search and citations" },
  github: { zh: "按论文 ID 搜索代码", en: "Find code by arXiv ID" },
  openalex: { zh: "开放学术目录检索", en: "Open scholarly catalog" },
  "google-scholar": { zh: "学术搜索与被引信息", en: "Scholarly search and cited-by links" },
  pwc: { zh: "论文代码、数据与榜单", en: "Code, datasets, and benchmarks" },
  "scholar-inbox": { zh: "个性化论文推送", en: "Personalized paper recommendations" },
  dblp: { zh: "计算机科学文献目录", en: "Computer science bibliography" },
  gotit: { zh: "论文阅读与批注讨论", en: "Paper reading and annotations" },
  pubpeer: { zh: "论文发表后评议", en: "Post-publication peer review" },
  prereview: { zh: "预印本开放评审", en: "Open preprint reviews" },
  openreview: { zh: "公开审稿与论文讨论", en: "Open peer review and discussion" },
  "immersive-translate": { zh: "论文与网页翻译", en: "Paper and webpage translation" },
  "zotero-bib": { zh: "在线生成参考文献", en: "Online bibliography builder" },
  "zotero-arxiv-reader": { zh: "Zotero 双语 AI 阅读", en: "Bilingual AI reading in Zotero" },
  zotmeta: { zh: "补全与修复元数据", en: "Complete and repair metadata" },
  "zotero-arxiv-workflow": { zh: "追踪发表与合并版本", en: "Track publications and merge versions" },
  zotarxiv: { zh: "导入论文与附件", en: "Import papers and attachments" },
  "hjfy-split-reader": { zh: "中英 PDF 分屏阅读", en: "Side-by-side bilingual PDF reading" },
  "zotero-convert-to-arxiv": { zh: "规范化 arXiv 条目", en: "Normalize arXiv entries" },
  "arxiv-marker": { zh: "查询正式发表信息", en: "Find publication details" },
  alphapulse: { zh: "显示论文热度与引用", en: "Paper popularity and citations" },
  "zotero-citation-tally": { zh: "多来源论文引用统计", en: "Citation counts from multiple sources" },
  xiaohongshu: { zh: "论文笔记与讨论搜索", en: "Find paper notes and discussions" },
  "x-search": { zh: "X 论文讨论搜索", en: "Find paper discussions on X" },
  "reddit-search": { zh: "Reddit 论文讨论搜索", en: "Find paper discussions on Reddit" },
  "zhihu-search": { zh: "知乎论文解读搜索", en: "Find paper explanations on Zhihu" },
  markxiv: { zh: "论文转纯文本", en: "Papers to plain text" },
  "arxiv-mcp": { zh: "arXiv MCP 检索与阅读", en: "arXiv search and reading via MCP" },
  "alphaxiv-mcp": { zh: "alphaXiv MCP 接入", en: "alphaXiv MCP integration" },
  deepxiv: { zh: "科研检索与数据服务", en: "Research search and data services" },
  "arxiv-rss": { zh: "生成论文 RSS 订阅", en: "Generate paper RSS feeds" },
  chinaxiv: { zh: "中国综合预印本平台", en: "Chinese multidisciplinary preprints" },
  biorxiv: { zh: "生物学预印本", en: "Biology preprints" },
  medrxiv: { zh: "医学与健康科学预印本", en: "Medicine and health preprints" },
  chemrxiv: { zh: "化学预印本", en: "Chemistry preprints" },
  techrxiv: { zh: "电气与计算机技术预印本", en: "Electrical and computing preprints" },
  engrxiv: { zh: "工程学预印本", en: "Engineering preprints" },
  eartharxiv: { zh: "地球科学预印本", en: "Earth science preprints" },
  agrirxiv: { zh: "农业科学预印本", en: "Agricultural science preprints" },
  ecoevorxiv: { zh: "生态与进化生物学预印本", en: "Ecology and evolution preprints" },
  psyarxiv: { zh: "心理学预印本", en: "Psychology preprints" },
  socarxiv: { zh: "社会科学工作论文", en: "Social science working papers" },
  ssrn: { zh: "多学科工作论文", en: "Multidisciplinary working papers" },
  econpapers: { zh: "经济学文献检索", en: "Economics literature search" },
  preprints: { zh: "综合学科预印本", en: "Multidisciplinary preprints" },
  ecsarxiv: { zh: "电化学与固态科学预印本", en: "Electrochemistry and solid-state preprints" },
  sportrxiv: { zh: "运动与体育科学预印本", en: "Sport and exercise science preprints" },
  edarxiv: { zh: "教育学预印本", en: "Education preprints" },
  philarchive: { zh: "哲学开放论文库", en: "Open philosophy archive" },
};
