export type ToolCategory =
  | "source"
  | "ai"
  | "agent"
  | "translate"
  | "search"
  | "discussion"
  | "discover"
  | "zotero"
  | "xiv";

export type LinkKind = "paper" | "search" | "hub";

export const DEFAULT_FAVORITES = [
  { id: "paperdance", url: "https://paperdance.org/" },
  { id: "arxivdaily", url: "https://www.arxivdaily.com/" },
  { id: "alphaxiv", url: "https://www.alphaxiv.org/" },
  { id: "hjfy", url: "https://hjfy.top/arxiv/2608.15875" },
  { id: "papers-cool", url: "https://papers.cool/arxiv/2608.15875" },
  { id: "arxivtldr", url: "https://arxivtldr.org/abs/2608.15875" },
];

export type ProbeStatus =
  | "verified"
  | "reachable"
  | "spa"
  | "cf"
  | "hub-only"
  | "down";

export type Tool = {
  id: string;
  name: string;
  nameZh: string;
  blurb: string;
  blurbZh: string;
  category: ToolCategory;
  additionalCategories?: ToolCategory[];
  kind: LinkKind;
  /** URL template. Tokens: {id} {titleEnc} {doi} */
  url: string;
  home: string;
  icon?: string;
  probe: ProbeStatus;
  probeNote: string;
  probeNoteZh: string;
  featured?: boolean;
  langs?: Array<"en" | "zh">;
};

export const CATEGORIES: Array<{
  id: ToolCategory | "all";
  label: string;
  labelZh: string;
}> = [
  { id: "all", label: "All", labelZh: "全部" },
  { id: "source", label: "Source", labelZh: "原文" },
  { id: "ai", label: "AIChat", labelZh: "AIChat" },
  { id: "discussion", label: "Discussion", labelZh: "讨论" },
  { id: "search", label: "Search", labelZh: "检索" },
  { id: "translate", label: "Translate", labelZh: "翻译" },
  { id: "discover", label: "Discover", labelZh: "发现" },
  { id: "xiv", label: "*Xiv", labelZh: "*Xiv" },
  { id: "agent", label: "Agent", labelZh: "Agent" },
  { id: "zotero", label: "Zotero", labelZh: "Zotero" },
];

export const PROBE_LABEL: Record<
  ProbeStatus,
  { en: string; zh: string }
> = {
  verified: { en: "Deep link verified", zh: "单篇深链已核验" },
  reachable: { en: "Reachable", zh: "站点可达" },
  spa: { en: "SPA — template likely", zh: "SPA，模板可用" },
  cf: { en: "Live (bot wall here)", zh: "真人可开（爬虫遇墙）" },
  "hub-only": { en: "Hub / browse", zh: "浏览型，无稳定深链" },
  down: { en: "Unreachable in probe", zh: "探测未通" },
};

// 学科平台只提供首页入口；图标来源见 public/icons/xiv/SOURCES.md。
const XIV_PLATFORMS = [
  { id: "chinaxiv", name: "ChinaXiv", home: "https://chinaxiv.org/", zh: "中国科学院支持的综合性预印本平台，开放分享多学科研究。", en: "CAS-supported preprint platform for sharing multidisciplinary research.", icon: "ico" },
  { id: "biorxiv", name: "bioRxiv", home: "https://www.biorxiv.org/", zh: "生物学预印本平台，涵盖遗传学、神经科学、细胞生物学等。", en: "Biology preprints covering genetics, neuroscience, cell biology, and more.", icon: "ico" },
  { id: "medrxiv", name: "medRxiv", home: "https://www.medrxiv.org/", zh: "医学与健康科学预印本平台，涵盖临床研究、流行病学等。", en: "Medical and health science preprints, including clinical research and epidemiology.", icon: "ico" },
  { id: "chemrxiv", name: "ChemRxiv", home: "https://chemrxiv.org/", zh: "化学预印本平台，涵盖有机化学、材料化学与交叉研究。", en: "Chemistry preprints spanning organic chemistry, materials, and related fields.", icon: "png" },
  { id: "techrxiv", name: "TechRxiv", home: "https://www.techrxiv.org/", zh: "IEEE 支持的技术预印本平台，面向电气工程、计算机科学等领域。", en: "IEEE-supported preprints in electrical engineering, computer science, and technology.", icon: "png" },
  { id: "engrxiv", name: "engrXiv", home: "https://engrxiv.org/", zh: "工程学预印本平台，开放分享机械、土木、电子等工程研究。", en: "Engineering preprints across mechanical, civil, electronic, and related disciplines.", icon: "png" },
  { id: "eartharxiv", name: "EarthArXiv", home: "https://eartharxiv.org/", zh: "地球科学预印本平台，涵盖地质学、气候科学与海洋科学等。", en: "Earth science preprints covering geology, climate, oceans, and related research.", icon: "png" },
  { id: "agrirxiv", name: "AgriRxiv", home: "https://www.cabidigitallibrary.org/journal/agrirxiv", zh: "农业科学预印本平台，涵盖作物、土壤、畜牧与食品研究。", en: "Agricultural science preprints on crops, soils, livestock, and food research.", icon: "png" },
  { id: "ecoevorxiv", name: "EcoEvoRxiv", home: "https://ecoevorxiv.org/", zh: "生态学、进化生物学与保护生物学的开放预印本平台。", en: "Open preprints in ecology, evolutionary biology, and conservation biology.", icon: "ico" },
  { id: "psyarxiv", name: "PsyArXiv", home: "https://osf.io/preprints/psyarxiv", zh: "心理学预印本平台，分享认知、行为、社会心理等领域研究。", en: "Psychology preprints covering cognition, behavior, and social psychology.", icon: "png" },
  { id: "socarxiv", name: "SocArXiv", home: "https://osf.io/preprints/socarxiv", zh: "社会科学开放论文平台，涵盖社会学及相关学科的工作论文。", en: "Open social science papers, including sociology and related working papers.", icon: "png" },
  { id: "ssrn", name: "SSRN", home: "https://www.ssrn.com/", zh: "多学科工作论文与预印本平台，以经济学、金融学和法学等见长。", en: "Working papers and preprints, especially in economics, finance, and law.", icon: "ico" },
  { id: "econpapers", name: "EconPapers", home: "https://econpapers.repec.org/", zh: "经济学文献平台，基于 RePEc 检索工作论文、期刊文章与相关研究。", en: "Economics literature from RePEc, including working papers, journal articles, and related research.", icon: "ico" },
  { id: "preprints", name: "Preprints.org", home: "https://www.preprints.org/", zh: "综合性预印本平台，覆盖自然科学、社会科学与人文学科。", en: "Multidisciplinary preprints across natural sciences, social sciences, and humanities.", icon: "png" },
  { id: "ecsarxiv", name: "ECSarXiv", home: "https://osf.io/preprints/ecsarxiv/", zh: "电化学与固态科学预印本平台，涵盖电池、能源材料等研究。", en: "Electrochemistry and solid-state science preprints, including batteries and energy materials.", icon: "png" },
  { id: "sportrxiv", name: "SportRxiv", home: "https://sportrxiv.org/", zh: "运动与体育科学预印本平台，涵盖运动表现、生理与训练研究。", en: "Sport and exercise science preprints on performance, physiology, and training.", icon: "ico" },
  { id: "edarxiv", name: "EdArXiv", home: "https://osf.io/preprints/edarxiv", zh: "教育学预印本平台，分享教学、学习科学与教育政策研究。", en: "Education preprints on teaching, learning sciences, and education policy.", icon: "png" },
  { id: "philarchive", name: "PhilArchive", home: "https://philarchive.org/", zh: "哲学开放论文库，收录伦理学、认识论、逻辑学等领域论文。", en: "Open philosophy archive with papers in ethics, epistemology, logic, and more.", icon: "png" },
];

export const TOOLS: Tool[] = [
  {
    id: "arxiv-abs",
    name: "arXiv Abstract",
    nameZh: "arXiv 摘要页",
    blurb: "Canonical abstract, versions, and download links.",
    blurbZh: "官方摘要页：版本、分类、下载入口。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/abs/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 · title matches",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-pdf",
    name: "arXiv PDF",
    nameZh: "arXiv PDF",
    blurb: "Official PDF of the current version.",
    blurbZh: "官方当前版本 PDF。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/pdf/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 PDF",
    probeNoteZh: "200 PDF",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-html",
    name: "arXiv HTML",
    nameZh: "arXiv HTML",
    blurb: "Experimental HTML5 rendering on arXiv itself.",
    blurbZh: "arXiv 官方实验性 HTML 阅读。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/html/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 HTML",
    probeNoteZh: "200 HTML",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-txt",
    name: "arXiv TXT",
    nameZh: "arXiv TXT",
    blurb: "Plain-text paper reading for lightweight browsing and copying.",
    blurbZh: "获取论文摘要信息，供 Agent 读取。",
    category: "agent",
    kind: "paper",
    url: "https://www.arxiv-txt.org/abs/{id}",
    home: "https://www.arxiv-txt.org/",
    probe: "hub-only",
    probeNote: "Paste an arXiv ID on the public site",
    probeNoteZh: "在公开网站粘贴 arXiv ID",
    langs: ["en"],
  },
  {
    id: "arxiv2md",
    name: "arXiv2MD",
    nameZh: "arXiv2MD",
    blurb: "Convert arXiv papers into Markdown for notes and AI workflows.",
    blurbZh: "将 arXiv 论文转换为 Markdown，方便笔记和 AI 工作流。",
    category: "agent",
    kind: "hub",
    url: "https://www.arxiv2md.org/",
    home: "https://www.arxiv2md.org/",
    icon: "icons/arxiv2md.ico",
    probe: "hub-only",
    probeNote: "Paste an arXiv ID on the public site",
    probeNoteZh: "在公开网站粘贴 arXiv ID",
    langs: ["en"],
  },
  {
    id: "arxiv-src",
    name: "arXiv Source",
    nameZh: "arXiv 源码包",
    blurb: "Author-submitted TeX source tarball.",
    blurbZh: "作者提交的 TeX 源码包。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/src/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "alphaxiv",
    name: "alphaXiv",
    nameZh: "alphaXiv",
    blurb: "A clean paper reading page with community notes and context.",
    blurbZh: "论文阅读与社区注释入口，适合快速了解上下文。",
    category: "ai",
    kind: "paper",
    url: "https://www.alphaxiv.org/abs/{id}",
    home: "https://www.alphaxiv.org/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need | alphaXiv",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "papers-cool",
    name: "Papers.cool",
    nameZh: "Cool Papers",
    blurb: "Immersive discovery plus Kimi-powered reading aids.",
    blurbZh: "沉浸式刷论文，Kimi 辅助阅读。",
    category: "ai",
    kind: "paper",
    url: "https://papers.cool/arxiv/{id}",
    home: "https://papers.cool/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need | Cool Papers",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["zh", "en"],
  },
  {
    id: "hjfy",
    name: "HJFY",
    nameZh: "幻觉翻译",
    blurb: "Chinese translations of arXiv papers with the original page layout.",
    blurbZh: "提供 arXiv 论文同页面布局中文",
    category: "translate",
    kind: "paper",
    url: "https://hjfy.top/arxiv/{id}",
    home: "https://hjfy.top/",
    probe: "verified",
    probeNote: "200 SPA; live pages render 幻觉翻译 for this id",
    probeNoteZh: "200，该 ID 可打开中文译文",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "chinarxiv",
    name: "ChinArXiv",
    nameZh: "ChinArXiv 翻译",
    blurb: "Paste an arXiv ID or PDF for bilingual translation. No deep link.",
    blurbZh: "粘贴 arXiv ID 或 PDF 做双语翻译。无稳定单篇 URL。",
    category: "translate",
    kind: "hub",
    url: "https://chinarxiv.chatpaper.top/",
    home: "https://chinarxiv.chatpaper.top/",
    probe: "hub-only",
    probeNote: "Home 200. /arxiv/{id} → 404. Paste ID in the form.",
    probeNoteZh: "首页 200；/arxiv/{id} 为 404，需在表单粘贴 ID",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "chatpaper",
    name: "ChatPaper",
    nameZh: "ChatPaper",
    blurb: "Daily AI paper feed with chat-on-paper.",
    blurbZh: "每日论文流 + 与论文对话。",
    category: "ai",
    kind: "hub",
    url: "https://chatpaper.com/",
    home: "https://chatpaper.com/",
    icon: "icons/chatpaper.png",
    probe: "hub-only",
    probeNote: "200. ?arxiv={id} still serves the homepage.",
    probeNoteZh: "200；带 arxiv 参数仍是首页",
    langs: ["zh", "en"],
  },
  {
    id: "iarxiv",
    name: "IArxiv",
    nameZh: "IArxiv",
    blurb: "An arXiv discovery service with account-based access.",
    blurbZh: "arXiv 论文发现服务，登录后访问。",
    category: "discover",
    kind: "hub",
    url: "https://iarxiv.org/",
    home: "https://iarxiv.org/",
    icon: "icons/iarxiv.ico",
    probe: "hub-only",
    probeNote: "Homepage requires sign-in.",
    probeNoteZh: "首页需登录。",
    langs: ["en"],
  },
  {
    id: "arxivdaily",
    name: "ArXiv Daily",
    nameZh: "ArXiv Daily",
    blurb: "Full-corpus daily digest with Chinese AI summaries.",
    blurbZh: "全量日更 + 中文 AI 摘要。按日浏览，无单篇深链。",
    category: "discover",
    kind: "hub",
    url: "https://www.arxivdaily.com/",
    home: "https://www.arxivdaily.com/",
    probe: "hub-only",
    probeNote: "Home 200. /paper/{id} → 404.",
    probeNoteZh: "首页 200；/paper/{id} 为 404",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "paperdance",
    name: "PaperDance",
    nameZh: "PaperDance",
    blurb: "Swipe arXiv like short videos — TLDR, figure, three takeaways.",
    blurbZh: "像刷短视频一样刷 arXiv：一句话、配图、三点。",
    category: "discover",
    kind: "hub",
    url: "https://paperdance.org/",
    home: "https://paperdance.org/",
    probe: "hub-only",
    probeNote: "/abs/{id} returns the same SPA shell. Feed, not a paper page.",
    probeNoteZh: "/abs/{id} 与首页同一套 SPA，无单篇页",
    featured: true,
    langs: ["zh", "en"],
  },
  {
    id: "arxivtldr",
    name: "ArXiv TLDR",
    nameZh: "ArXiv TLDR",
    blurb: "Swap arxiv.org → arxivtldr.org for a structured TLDR.",
    blurbZh: "把域名换成 arxivtldr.org，得到结构化 TLDR。",
    category: "ai",
    kind: "paper",
    url: "https://arxivtldr.org/abs/{id}",
    home: "https://arxivtldr.org/",
    probe: "verified",
    probeNote: "200 · TL;DR: Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxivxplorer",
    name: "ArXiv Xplorer",
    nameZh: "ArXiv Xplorer",
    blurb: "Semantic search over the whole arXiv corpus.",
    blurbZh: "全库语义搜索。无 /abs/{id} 深链。",
    category: "search",
    kind: "search",
    url: "https://arxivxplorer.com/?q={id}",
    home: "https://arxivxplorer.com/",
    probe: "reachable",
    probeNote: "Home 200. /abs/{id} and /paper/{id} → 404. ?q= works.",
    probeNoteZh: "首页 200；/abs 与 /paper 404；?q= 可用",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-bshk",
    name: "arXiv BSHK",
    nameZh: "arXiv BSHK 语义搜索",
    blurb: "In-browser semantic search (1M+ papers, WebGPU).",
    blurbZh: "浏览器内语义搜索（百万篇，WebGPU）。",
    category: "search",
    kind: "hub",
    url: "https://arxiv.bshk.app/",
    home: "https://arxiv.bshk.app/",
    probe: "hub-only",
    probeNote: "SPA 200. /abs/{id} is the same shell, not a paper page.",
    probeNoteZh: "SPA 首页；/abs/{id} 不是论文页",
    featured: true,
    langs: ["en"],
  },
  {
    id: "scirate",
    name: "SciRate",
    nameZh: "SciRate",
    blurb: "Community ratings and comments on arXiv papers.",
    blurbZh: "arXiv 论文评分与讨论。",
    category: "discussion",
    kind: "paper",
    url: "https://scirate.com/arxiv/{id}",
    home: "https://scirate.com/",
    probe: "cf",
    probeNote: "Canonical /arxiv/{id}. Datacenter hit Cloudflare.",
    probeNoteZh: "标准深链 /arxiv/{id}；机房 IP 遇 Cloudflare",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxivisual",
    name: "arXivisual",
    nameZh: "arXivisual",
    blurb: "Turns a paper into a visual video explanation. URL-swap trick.",
    blurbZh: "把论文做成可视化讲解视频。arxiv → arxivisual。",
    category: "ai",
    kind: "paper",
    url: "https://arxivisual.org/abs/{id}",
    home: "https://arxivisual.org/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need · arXivisual",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "hf-papers",
    name: "Hugging Face Papers",
    nameZh: "Hugging Face Papers",
    blurb: "Upvotes, discussion, linked models, datasets, and spaces.",
    blurbZh: "社区投票、讨论，以及关联模型 / 数据集 / Space。",
    category: "discussion",
    kind: "paper",
    url: "https://huggingface.co/papers/{id}",
    home: "https://huggingface.co/papers",
    icon: "icons/hf-papers.ico",
    probe: "verified",
    probeNote: "200 · Paper page - Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "ar5iv",
    name: "ar5iv",
    nameZh: "ar5iv HTML",
    blurb: "Clean HTML5 conversion of arXiv TeX. Great on mobile.",
    blurbZh: "TeX 转 HTML5，移动端友好。",
    category: "source",
    kind: "paper",
    url: "https://ar5iv.labs.arxiv.org/html/{id}",
    home: "https://ar5iv.labs.arxiv.org/",
    probe: "verified",
    probeNote: "200 · [1706.03762] Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    langs: ["en"],
  },
  {
    id: "emergent-mind",
    name: "Emergent Mind",
    nameZh: "Emergent Mind",
    blurb: "AI summaries, follow-ups, and whiteboard explainers.",
    blurbZh: "AI 摘要、追问和白板讲解。",
    category: "discover",
    kind: "paper",
    url: "https://www.emergentmind.com/papers/{id}",
    home: "https://www.emergentmind.com/",
    probe: "verified",
    probeNote: "200 · Transformer: Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    langs: ["en"],
  },
  {
    id: "talk2arxiv",
    name: "Talk2Arxiv",
    nameZh: "Talk2Arxiv",
    blurb: "URL-swap RAG chat: arxiv.org → talk2arxiv.org.",
    blurbZh: "改域名为 talk2arxiv.org 即可 RAG 对话。",
    category: "ai",
    kind: "paper",
    url: "https://www.talk2arxiv.org/abs/{id}",
    home: "https://www.talk2arxiv.org/",
    probe: "reachable",
    probeNote: "200 Talk2Arxiv (generic title)",
    probeNoteZh: "200，通用标题",
    langs: ["en"],
  },
  {
    id: "sciencecast",
    name: "ScienceCast",
    nameZh: "ScienceCast",
    blurb: "Watch and share research videos linked to arXiv and bioRxiv preprints.",
    blurbZh: "科研视频讲解平台，观看和分享 arXiv、bioRxiv 预印本的研究介绍。",
    category: "ai",
    kind: "hub",
    url: "https://www.sciencecast.org/",
    home: "https://www.sciencecast.org/",
    icon: "icons/sciencecast.webp",
    probe: "hub-only",
    probeNote: "Research video platform homepage.",
    probeNoteZh: "科研视频平台首页。",
    langs: ["en"],
  },
  {
    id: "explainpaper",
    name: "Explainpaper",
    nameZh: "Explainpaper",
    blurb: "Highlight a passage, get a plain-language explanation.",
    blurbZh: "划选难句，立刻得到通俗解释。",
    category: "ai",
    kind: "hub",
    url: "https://www.explainpaper.com/",
    home: "https://www.explainpaper.com/",
    probe: "hub-only",
    probeNote: "200. Upload / open a PDF — no arXiv ID route.",
    probeNoteZh: "200；需上传 PDF，无 ID 路由",
    langs: ["en"],
  },
  {
    id: "scispace",
    name: "SciSpace",
    nameZh: "SciSpace",
    blurb: "Copilot reader and search across papers.",
    blurbZh: "论文 Copilot 阅读与检索。",
    category: "ai",
    kind: "search",
    url: "https://typeset.io/search?q={id}",
    home: "https://scispace.com/",
    probe: "reachable",
    probeNote: "Search URL 200. Direct /papers/ slug not stable.",
    probeNoteZh: "搜索 URL 200；直接 slug 不稳定",
    langs: ["en"],
  },
  {
    id: "chatdoc",
    name: "ChatDOC",
    nameZh: "ChatDOC",
    blurb: "Chat with documents and find answers with cited sources.",
    blurbZh: "文档问答与阅读，回答附原文引用。",
    category: "ai",
    kind: "hub",
    url: "https://chatdoc.com/",
    home: "https://chatdoc.com/",
    icon: "icons/chatdoc.ico",
    probe: "hub-only",
    probeNote: "Upload a document on the public site.",
    probeNoteZh: "在网站上传文档。",
    langs: ["en"],
  },
  {
    id: "consensus",
    name: "Consensus",
    nameZh: "Consensus",
    blurb: "Ask a question, get cited yes/no evidence from papers.",
    blurbZh: "提问，从论文里抽出有引用的证据。",
    category: "search",
    kind: "search",
    url: "https://consensus.app/search/?q={titleEnc}",
    home: "https://consensus.app/",
    probe: "cf",
    probeNote: "Home 200; search Cloudflare-walled here.",
    probeNoteZh: "首页 200；搜索遇墙",
    langs: ["en"],
  },
  {
    id: "litmaps",
    name: "Litmaps",
    nameZh: "Litmaps",
    blurb: "Explore citation maps and discover related research.",
    blurbZh: "探索论文的引文网络，发现相关文献与研究脉络。",
    category: "search",
    kind: "hub",
    url: "https://app.litmaps.com/preview",
    home: "https://app.litmaps.com/preview",
    icon: "icons/litmaps.png",
    probe: "hub-only",
    probeNote: "Public preview page without a fixed paper identifier.",
    probeNoteZh: "公开预览页，不指定固定论文编号。",
    langs: ["en"],
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    nameZh: "Connected Papers",
    blurb: "Visual graph of similar papers from a seed.",
    blurbZh: "从一篇种子论文画出相似论文图。",
    category: "discover",
    kind: "paper",
    url: "https://www.connectedpapers.com/api/redirect/arxiv/{id}",
    home: "https://www.connectedpapers.com/",
    icon: "icons/connected-papers.ico",
    probe: "spa",
    probeNote: "Redirect to the paper using its arXiv ID.",
    probeNoteZh: "通过 arXiv ID 重定向到对应论文。",
    langs: ["en"],
  },
  {
    id: "inciteful",
    name: "Inciteful",
    nameZh: "Inciteful",
    blurb: "Citation-network explorer. Accepts arxiv: id.",
    blurbZh: "引文网络探索，支持 arxiv:id。",
    category: "discover",
    kind: "search",
    url: "https://inciteful.xyz/?id=arxiv:{id}",
    home: "https://inciteful.xyz/",
    probe: "spa",
    probeNote: "SPA 200 for ?id=arxiv:{id}",
    probeNoteZh: "SPA 200",
    langs: ["en"],
  },
  {
    id: "paperscape",
    name: "Paperscape",
    nameZh: "Paperscape",
    blurb: "Map of all arXiv papers as a citation landscape.",
    blurbZh: "把整个 arXiv 画成引用地图。",
    category: "discover",
    kind: "hub",
    url: "https://paperscape.org/",
    home: "https://paperscape.org/",
    probe: "reachable",
    probeNote: "200 Paperscape",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "papermatch",
    name: "PaperMatch",
    nameZh: "PaperMatch",
    blurb: "Semantic similar-paper search from text or an arXiv ID.",
    blurbZh: "用自然语言或 arXiv ID 找相似论文。",
    category: "discover",
    kind: "hub",
    url: "https://papermatch.me/",
    home: "https://papermatch.me/",
    icon: "icons/papermatch.ico",
    probe: "hub-only",
    probeNote: "200. /{id} is the same SPA homepage.",
    probeNoteZh: "200；/{id} 仍是首页 SPA",
    langs: ["en"],
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    nameZh: "Semantic Scholar",
    blurb: "Search by paper title for TLDR, citations, and related research.",
    blurbZh: "按论文标题检索摘要、引用与相关研究。",
    category: "search",
    kind: "search",
    url: "https://www.semanticscholar.org/search?q={titleEnc}",
    home: "https://www.semanticscholar.org/",
    icon: "icons/semantic-scholar.png",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "github",
    name: "GitHub Search",
    nameZh: "GitHub Search",
    blurb: "Find open-source repositories mentioning the arXiv ID.",
    blurbZh: "按 arXiv ID 查找相关开源仓库与论文实现。",
    category: "search",
    kind: "search",
    url: "https://github.com/search?q={id}&type=repositories",
    home: "https://github.com/search",
    icon: "icons/github.ico",
    probe: "reachable",
    probeNote: "Repository search using the arXiv ID.",
    probeNoteZh: "按 arXiv ID 搜索仓库。",
    langs: ["en"],
  },
  {
    id: "openalex",
    name: "OpenAlex",
    nameZh: "OpenAlex",
    blurb: "Search the open scholarly catalog by paper title.",
    blurbZh: "按论文标题检索开放学术目录与相关研究。",
    category: "search",
    kind: "search",
    url: "https://openalex.org/works?filter=default.search:{titleEnc}",
    home: "https://openalex.org/",
    icon: "icons/openalex.png",
    probe: "spa",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "google-scholar",
    name: "Google Scholar",
    nameZh: "Google Scholar",
    blurb: "Lookup by arXiv id — cited-by and versions.",
    blurbZh: "按 arXiv ID 查找被引与版本。",
    category: "search",
    kind: "search",
    url: "https://scholar.google.com/scholar_lookup?arxiv_id={id}",
    home: "https://scholar.google.com/",
    icon: "icons/google-scholar.ico",
    probe: "verified",
    probeNote: "200 Google Scholar",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "pwc",
    name: "Papers with Code",
    nameZh: "Papers with Code",
    blurb: "Implementations, datasets, and leaderboards.",
    blurbZh: "实现、数据集与榜单。",
    category: "ai",
    kind: "paper",
    url: "https://paperswithcode.co/paper/{id}",
    home: "https://paperswithcode.co/",
    icon: "icons/papers-with-code.png",
    probe: "spa",
    probeNote: "Paper route by arXiv ID.",
    probeNoteZh: "按 arXiv ID 打开论文页。",
    langs: ["en"],
  },
  {
    id: "scholar-inbox",
    name: "Scholar Inbox",
    nameZh: "Scholar Inbox",
    blurb: "Personalized daily digest across arXiv and sibling servers.",
    blurbZh: "按兴趣推送 arXiv / bioRxiv / medRxiv 等。",
    category: "discover",
    kind: "hub",
    url: "https://www.scholar-inbox.com/",
    home: "https://www.scholar-inbox.com/",
    probe: "spa",
    probeNote: "SPA 200 Scholar Inbox",
    probeNoteZh: "SPA 200",
    langs: ["en"],
  },
  {
    id: "dblp",
    name: "DBLP",
    nameZh: "DBLP",
    blurb: "Computer science bibliography search.",
    blurbZh: "计算机科学文献目录。",
    category: "search",
    kind: "search",
    url: "https://dblp.org/search?q={id}",
    home: "https://dblp.org/",
    probe: "reachable",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "gotit",
    name: "GotIt",
    nameZh: "GotIt",
    blurb: "Read arXiv papers and discuss them with the research community.",
    blurbZh: "在线阅读 arXiv 论文，参与论文批注与学术交流。",
    category: "discussion",
    kind: "paper",
    url: "https://gotit.pub/view/{id}",
    home: "https://gotit.pub/",
    icon: "icons/gotit.png",
    probe: "spa",
    probeNote: "Paper route uses the arXiv ID.",
    probeNoteZh: "论文路由需要 arXiv ID。",
    langs: ["en"],
  },
  {
    id: "prereview",
    name: "PREreview",
    nameZh: "PREreview",
    blurb: "Write an open review of an arXiv preprint.",
    blurbZh: "为 arXiv 预印本撰写开放评审与学术反馈。",
    category: "discussion",
    kind: "paper",
    url: "https://prereview.org/preprints/doi-10.48550-arxiv.{id}/write-a-prereview",
    home: "https://prereview.org/",
    icon: "icons/prereview.svg",
    probe: "spa",
    probeNote: "Preprint review form using its arXiv DOI.",
    probeNoteZh: "使用 arXiv DOI 打开预印本评审表单。",
    langs: ["en"],
  },
  {
    id: "pubpeer",
    name: "PubPeer",
    nameZh: "PubPeer",
    blurb: "Search post-publication reviews and research discussions by arXiv ID.",
    blurbZh: "按 arXiv ID 检索论文发表后的评议与学术讨论。",
    category: "discussion",
    kind: "search",
    url: "https://www.pubpeer.com/search?q={id}",
    home: "https://www.pubpeer.com/",
    icon: "icons/pubpeer.png",
    probe: "reachable",
    probeNote: "Search URL using the arXiv ID.",
    probeNoteZh: "按 arXiv ID 搜索。",
    langs: ["en"],
  },
  {
    id: "openreview",
    name: "OpenReview",
    nameZh: "OpenReview",
    blurb: "Peer-review forum search (when the paper was submitted).",
    blurbZh: "按论文标题查找公开审稿与讨论。",
    category: "discussion",
    kind: "search",
    url: "https://openreview.net/search?term={titleEnc}",
    home: "https://openreview.net/",
    icon: "icons/openreview.png",
    probe: "reachable",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "immersive-translate",
    name: "Immersive Translate",
    nameZh: "沉浸式翻译",
    blurb: "Translate papers and web documents with the Babel Doc workspace.",
    blurbZh: "使用 Babel Doc 翻译论文和网页文档。",
    category: "translate",
    kind: "hub",
    url: "https://app.immersivetranslate.com/babel-doc/",
    home: "https://app.immersivetranslate.com/babel-doc/",
    probe: "reachable",
    probeNote: "Public Babel Doc entry",
    probeNoteZh: "公开 Babel Doc 入口",
    langs: ["zh", "en"],
  },
  {
    id: "zotero-bib",
    name: "ZoteroBib",
    nameZh: "ZoteroBib",
    blurb: "Quick bibliography builder without installing a reference manager.",
    blurbZh: "无需安装客户端即可快速生成参考文献。",
    category: "source",
    kind: "hub",
    url: "https://zbib.org/",
    home: "https://zbib.org/",
    icon: "icons/zotero.ico",
    probe: "reachable",
    probeNote: "Public bibliography builder",
    probeNoteZh: "公开参考文献生成器",
    langs: ["en"],
  },
  {
    id: "zotero-arxiv-reader",
    name: "arXiv Reader",
    nameZh: "arXiv Reader",
    blurb: "Fetch arXiv HTML for bilingual AI reading inside Zotero.",
    blurbZh: "获取 arXiv HTML，在 Zotero 内进行中英双语 AI 阅读。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/TheoCUC/zotero-arxiv-reader",
    home: "https://github.com/TheoCUC/zotero-arxiv-reader",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotmeta",
    name: "ZotMeta",
    nameZh: "ZotMeta",
    blurb: "Complete and repair Zotero metadata from DOI, ISBN, or arXiv IDs.",
    blurbZh: "根据 DOI、ISBN 或 arXiv ID 补全和修复 Zotero 元数据。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/RoadToDream/ZotMeta",
    home: "https://github.com/RoadToDream/ZotMeta",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotero-arxiv-workflow",
    name: "arXiv Workflow",
    nameZh: "arXiv Workflow",
    blurb: "Track published versions and update metadata and PDFs in Zotero.",
    blurbZh: "追踪正式发表版本，更新 Zotero 元数据和 PDF，并合并版本。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/AllanChain/zotero-arxiv-workflow",
    home: "https://github.com/AllanChain/zotero-arxiv-workflow",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotarxiv",
    name: "ZotarXiv",
    nameZh: "ZotarXiv",
    blurb: "Import arXiv IDs or URLs with PDFs, BibTeX, and alphaXiv links.",
    blurbZh: "通过 arXiv ID/URL 导入 PDF、BibTeX 和 alphaXiv 链接。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/zhanghm1995/ZotarXiv",
    home: "https://github.com/zhanghm1995/ZotarXiv",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "hjfy-split-reader",
    name: "HJFY Split Reader",
    nameZh: "HJFY Split Reader",
    blurb: "Read the original PDF and HJFY Chinese PDF side by side in Zotero.",
    blurbZh: "在 Zotero 内分屏阅读原文 PDF 和幻觉翻译中文 PDF。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/Infinity4B/zotero-hjfy-split-reader",
    home: "https://github.com/Infinity4B/zotero-hjfy-split-reader",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["zh", "en"],
  },
  {
    id: "zotero-convert-to-arxiv",
    name: "Convert to arXiv",
    nameZh: "Convert to arXiv",
    blurb: "Normalize an existing Zotero item as a standard arXiv preprint.",
    blurbZh: "将已有 Zotero 条目规范化为标准 arXiv Preprint。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/EricJin2002/zotero-convert-to-arxiv",
    home: "https://github.com/EricJin2002/zotero-convert-to-arxiv",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "arxiv-marker",
    name: "arxiv-marker",
    nameZh: "arxiv-marker",
    blurb: "Find final venues, DOI, and CCF/CORE metadata for arXiv papers.",
    blurbZh: "查询 arXiv 论文最终会议/期刊、DOI、CCF/CORE 等信息。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/lelelelelelelelelelelelele/arxiv-marker",
    home: "https://github.com/lelelelelelelelelelelelele/arxiv-marker",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "alphapulse",
    name: "AlphaPulse",
    nameZh: "AlphaPulse",
    blurb: "Show alphaXiv popularity and citation signals inside Zotero.",
    blurbZh: "在 Zotero 中显示 alphaXiv 热度、引用量等指标。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/IrisM6/AlphaPulse",
    home: "https://github.com/IrisM6/AlphaPulse",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotero-citation-tally",
    name: "Citation Tally",
    nameZh: "Citation Tally",
    blurb: "Show citation counts from Crossref, Semantic Scholar, and INSPIRE in Zotero.",
    blurbZh: "在 Zotero 中显示 Crossref、Semantic Scholar 和 INSPIRE 的论文引用次数。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/daeh/zotero-citation-tally",
    home: "https://github.com/daeh/zotero-citation-tally",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "xiaohongshu",
    name: "Xiaohongshu",
    nameZh: "小红书搜索",
    blurb: "Search public paper discussions and reading notes by title.",
    blurbZh: "按论文标题搜索公开笔记、解读和讨论。",
    category: "discussion",
    kind: "search",
    url: "https://www.xiaohongshu.com/search_result?keyword={titleEnc}",
    home: "https://www.xiaohongshu.com/",
    probe: "reachable",
    probeNote: "Title search URL",
    probeNoteZh: "论文标题搜索入口",
    langs: ["zh"],
  },
  {
    id: "x-search",
    name: "X Search",
    nameZh: "X 讨论搜索",
    blurb: "Search public discussions about the paper title on X.",
    blurbZh: "按论文标题搜索 X 上的公开讨论。",
    category: "discussion",
    kind: "search",
    url: "https://x.com/search?q={titleEnc}",
    home: "https://x.com/",
    icon: "icons/x-search.png",
    probe: "reachable",
    probeNote: "Title search URL",
    probeNoteZh: "论文标题搜索入口",
    langs: ["en"],
  },
  {
    id: "reddit-search",
    name: "Reddit Search",
    nameZh: "Reddit 搜索",
    blurb: "Find community discussions about a paper by its title.",
    blurbZh: "按论文标题搜索 Reddit 社区的解读与讨论。",
    category: "discussion",
    kind: "search",
    url: "https://www.reddit.com/search/?q={titleEnc}",
    home: "https://www.reddit.com/",
    icon: "icons/reddit.png",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "zhihu-search",
    name: "Zhihu Search",
    nameZh: "知乎搜索",
    blurb: "Find Chinese explanations and discussions by paper title.",
    blurbZh: "按论文标题搜索知乎上的论文解读与讨论。",
    category: "discussion",
    kind: "search",
    url: "https://www.zhihu.com/search?type=content&q={titleEnc}",
    home: "https://www.zhihu.com/",
    icon: "icons/zhihu.ico",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["zh"],
  },
];

TOOLS.push(
  {
    id: "markxiv", name: "MarkXiv", nameZh: "MarkXiv",
    blurb: "Convert papers to plain Markdown text for agents.", blurbZh: "论文转纯文本（Markdown），便于 Agent 读取。",
    category: "agent", kind: "hub", url: "https://markxiv.org/", home: "https://markxiv.org/",
    probe: "hub-only", probeNote: "Public tool", probeNoteZh: "公共工具入口",
  },
  {
    id: "arxiv-mcp", name: "arxiv-mcp", nameZh: "arxiv-mcp",
    blurb: "Search and read arXiv papers through MCP.", blurbZh: "通过 MCP 检索、下载和阅读 arXiv 论文。",
    category: "agent", kind: "hub", url: "https://github.com/blazickjp/arxiv-mcp-server", home: "https://github.com/blazickjp/arxiv-mcp-server",
    probe: "hub-only", probeNote: "MCP repository", probeNoteZh: "MCP 项目仓库",
  },
  {
    id: "alphaxiv-mcp", name: "alphaxiv-mcp", nameZh: "alphaxiv-mcp",
    blurb: "Connect agents to alphaXiv through MCP.", blurbZh: "将 Agent 接入 alphaXiv MCP 服务。",
    category: "agent", kind: "hub", url: "https://www.alphaxiv.org/docs/mcp", home: "https://www.alphaxiv.org/docs/mcp",
    probe: "hub-only", probeNote: "MCP documentation", probeNoteZh: "MCP 接入文档",
  },
  {
    id: "deepxiv", name: "DeepXiv", nameZh: "DeepXiv",
    blurb: "Research data for retrieval and agents.", blurbZh: "面向检索与 Agent 的科研数据入口。",
    category: "agent", kind: "hub", url: "https://data.rag.ac.cn/", home: "https://data.rag.ac.cn/",
    icon: "icons/deepxiv.svg",
    probe: "hub-only", probeNote: "Research data portal", probeNoteZh: "科研数据平台",
  },
  {
    id: "arxiv-rss", name: "arxiv-rss", nameZh: "arxiv-rss 订阅生成",
    blurb: "Generate custom arXiv RSS feeds.", blurbZh: "生成自定义 arXiv RSS 订阅。",
    category: "discover", kind: "hub", url: "https://ronpay.github.io/arxiv-rss-feed-generator/", home: "https://ronpay.github.io/arxiv-rss-feed-generator/",
    probe: "hub-only", probeNote: "RSS generator", probeNoteZh: "RSS 订阅生成器",
  },
);

// 独立平台是公共入口，不构造当前 arXiv 论文的跨站深链。
TOOLS.push(...XIV_PLATFORMS.map((platform): Tool => ({
  id: platform.id,
  name: platform.name,
  nameZh: platform.name,
  blurb: platform.en,
  blurbZh: platform.zh,
  category: "xiv",
  kind: "hub",
  url: platform.home,
  home: platform.home,
  icon: `icons/xiv/${platform.id}.${platform.icon}`,
  probe: "hub-only",
  probeNote: "Independent preprint platform",
  probeNoteZh: "独立预印本平台",
})));

export const PAPER_CATEGORIES = ["discussion", "ai", "search", "translate"] as const;

// 与首页使用相同的类别成员；公共工具保留其配置网址，不构造论文深链。
export const PAPER_TOOLS = TOOLS.filter((tool) => PAPER_CATEGORIES.some((category) =>
  tool.category === category || tool.additionalCategories?.includes(category),
));

export type ExtraLink = {
  paperId: string;
  name: string;
  nameZh: string;
  url: string;
  blurb: string;
  blurbZh: string;
};

export const EXTRAS: ExtraLink[] = [
  {
    paperId: "1706.03762",
    name: "The Annotated Transformer",
    nameZh: "The Annotated Transformer",
    url: "https://nlp.seas.harvard.edu/annotated-transformer/",
    blurb: "Harvard NLP line-by-line implementation of this paper.",
    blurbZh: "Harvard NLP 逐行实现。",
  },
  {
    paperId: "1706.03762",
    name: "The Illustrated Transformer",
    nameZh: "图解 Transformer",
    url: "https://jalammar.github.io/illustrated-transformer/",
    blurb: "Jay Alammar’s visual walkthrough.",
    blurbZh: "Jay Alammar 的图解。",
  },
  {
    paperId: "1706.03762",
    name: "NeurIPS 2017",
    nameZh: "NeurIPS 2017 正式版",
    url: "https://proceedings.neurips.cc/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
    blurb: "Conference proceedings page. Title verified.",
    blurbZh: "会议正式版，标题已核验。",
  },
];

export const EXAMPLE_PAPERS: Array<{
  id: string;
  title: string;
  year: string;
  href?: string;
}> = [
  { id: "1706.03762", title: "Attention Is All You Need", year: "2017" },
  { id: "2303.08774", title: "GPT-4", year: "2023" },
  { id: "2504.16054", title: "Pi05", year: "2025" },
  { id: "2608.15875", title: "GigaBrain-0.7", year: "2026"},
];

export type ToolContext = {
  id: string;
  title?: string;
  doi?: string;
};

export function buildToolUrl(tool: Tool, ctx: ToolContext): string {
  const titleEnc = encodeURIComponent(ctx.title || ctx.id);
  return tool.url
    .replaceAll("{id}", ctx.id)
    .replaceAll("{titleEnc}", titleEnc)
    .replaceAll("{doi}", ctx.doi ?? `10.48550/arXiv.${ctx.id}`);
}

export function getGitHubRepository(href: string): string | null {
  try {
    const url = new URL(href);
    const parts = url.pathname.split("/").filter(Boolean);
    if (url.hostname !== "github.com" || parts.length !== 2) return null;
    return `${parts[0]}/${parts[1].replace(/\.git$/, "")}`;
  } catch {
    return null;
  }
}

export function countByProbe(status: ProbeStatus): number {
  return TOOLS.filter((t) => t.probe === status).length;
}
