export { buildToolUrl, catalyzeXSlug } from "./paper-navigation.ts";

export type ToolCategory =
  | "source"
  | "ai-summary"
  | "ai-chat"
  | "agent"
  | "translate"
  | "search"
  | "discussion"
  | "discover"
  | "subscribe"
  | "zotero"
  | "xiv"
  | "tool";

export type LinkKind = "paper" | "search" | "hub";

export const DEFAULT_FAVORITES = [
  { id: "alphaxiv", url: "https://www.alphaxiv.org/" },
  { id: "paperlayer", url: "https://paperlayer.ai/" },
  { id: "hjfy", url: "https://hjfy.top/arxiv/2608.15875" },
  { id: "papers-cool", url: "https://papers.cool/arxiv/2608.15875" },
  { id: "arxivdaily", url: "https://www.arxivdaily.com/" },
  { id: "paperdance", url: "https://paperdance.org/" },
  { id: "arxivtldr", url: "https://arxivtldr.org/abs/2608.15875" },
  { id: "arxiv-rss", url: "https://ronpay.github.io/arxiv-rss-feed-generator/" },
  { id: "pith", url: "https://pith.science/" },
];

export type ProbeStatus =
  | "verified"
  | "reachable"
  | "spa"
  | "cf"
  | "hub-only"
  | "down";

export type Tool = {
  id: string;
  name: string;
  nameZh: string;
  blurb: string;
  blurbZh: string;
  category: ToolCategory;
  additionalCategories?: ToolCategory[];
  kind: LinkKind;
  /** URL template. Tokens: {id} {titleEnc} {doi} */
  url: string;
  home: string;
  icon?: string;
  probe: ProbeStatus;
  probeNote: string;
  probeNoteZh: string;
  featured?: boolean;
  langs?: Array<"en" | "zh">;
};

export const CATEGORIES: Array<{
  id: ToolCategory | "all";
  label: string;
  labelZh: string;
}> = [
  { id: "all", label: "All", labelZh: "全部" },
  { id: "source", label: "Source", labelZh: "原文" },
  { id: "ai-summary", label: "AI Summary", labelZh: "AI解读" },
  { id: "ai-chat", label: "AI Chat", labelZh: "AI问答" },
  { id: "search", label: "Search", labelZh: "检索" },
  { id: "discussion", label: "Discussion", labelZh: "讨论" },
  { id: "translate", label: "Translate", labelZh: "翻译" },
  { id: "discover", label: "Discover", labelZh: "发现" },
  { id: "subscribe", label: "Subscribe", labelZh: "订阅" },
  { id: "xiv", label: "Xiv Universe", labelZh: "Xiv宇宙" },
  { id: "agent", label: "Agent", labelZh: "Agent" },
  { id: "zotero", label: "Zotero", labelZh: "Zotero" },
  { id: "tool", label: "Tool", labelZh: "Tool" },
];

export const PROBE_LABEL: Record<
  ProbeStatus,
  { en: string; zh: string }
> = {
  verified: { en: "Deep link verified", zh: "单篇深链已核验" },
  reachable: { en: "Reachable", zh: "站点可达" },
  spa: { en: "SPA — template likely", zh: "SPA，模板可用" },
  cf: { en: "Live (bot wall here)", zh: "真人可开（爬虫遇墙）" },
  "hub-only": { en: "Hub / browse", zh: "浏览型，无稳定深链" },
  down: { en: "Unreachable in probe", zh: "探测未通" },
};

// 学科平台只提供首页入口；图标来源见 public/icons/xiv/SOURCES.md。
const XIV_PLATFORMS = [
  { id: "chinaxiv", name: "ChinaXiv", home: "https://chinaxiv.org/", zh: "中科院体系的综合预印本平台。", en: "A multidisciplinary preprint platform with Chinese research.", icon: "ico" },
  { id: "biorxiv", name: "bioRxiv", home: "https://www.biorxiv.org/", zh: "生命科学预印本的核心入口。", en: "A core preprint server for life sciences.", icon: "ico" },
  { id: "medrxiv", name: "medRxiv", home: "https://www.medrxiv.org/", zh: "医学、临床和公共卫生预印本入口。", en: "Preprints for medicine, clinical work, and public health.", icon: "ico" },
  { id: "chemrxiv", name: "ChemRxiv", home: "https://chemrxiv.org/", zh: "化学领域的主流预印本平台。", en: "A major preprint platform for chemistry.", icon: "png" },
  { id: "techrxiv", name: "TechRxiv", home: "https://www.techrxiv.org/", zh: "电气、电子和计算机技术预印本。", en: "Preprints in electrical, electronic, and computing technology.", icon: "png" },
  { id: "engrxiv", name: "engrXiv", home: "https://engrxiv.org/", zh: "工程学科的开放预印本库。", en: "Open preprints across engineering.", icon: "png" },
  { id: "eartharxiv", name: "EarthArXiv", home: "https://eartharxiv.org/", zh: "地球、环境和行星科学预印本。", en: "Preprints for Earth, environmental, and planetary science.", icon: "png" },
  { id: "agrirxiv", name: "AgriRxiv", home: "https://www.cabidigitallibrary.org/journal/agrirxiv", zh: "农业、食品和应用科学预印本。", en: "Preprints for agriculture, food, and applied science.", icon: "png" },
  { id: "ecoevorxiv", name: "EcoEvoRxiv", home: "https://ecoevorxiv.org/", zh: "生态、进化与保育生物学预印本。", en: "Preprints for ecology, evolution, and conservation.", icon: "ico" },
  { id: "psyarxiv", name: "PsyArXiv", home: "https://osf.io/preprints/psyarxiv", zh: "心理学与行为科学开放预印本。", en: "Open preprints in psychology and behavioral science.", icon: "png" },
  { id: "socarxiv", name: "SocArXiv", home: "https://osf.io/preprints/socarxiv", zh: "社会学与社会科学工作论文。", en: "Working papers in sociology and social science.", icon: "png" },
  { id: "ssrn", name: "SSRN", home: "https://www.ssrn.com/", zh: "法律、经济、金融和社会科学工作论文。", en: "Working papers in law, economics, finance, and social science.", icon: "ico" },
  { id: "econpapers", name: "EconPapers", home: "https://econpapers.repec.org/", zh: "RePEc 经济学检索，工作论文尤其好用。", en: "RePEc search for economics, especially working papers.", icon: "ico", category: "search" as ToolCategory },
  { id: "preprints", name: "Preprints.org", home: "https://www.preprints.org/", zh: "覆盖多学科的综合预印本平台。", en: "A multidisciplinary preprint platform.", icon: "png" },
  { id: "ecsarxiv", name: "ECSarXiv", home: "https://osf.io/preprints/ecsarxiv/", zh: "电化学与固态科学预印本。", en: "Preprints for electrochemistry and solid-state science.", icon: "png" },
  { id: "sportrxiv", name: "SportRxiv", home: "https://sportrxiv.org/", zh: "运动科学与人体表现研究预印本。", en: "Preprints for sport science and human performance.", icon: "ico" },
  { id: "edarxiv", name: "EdArXiv", home: "https://osf.io/preprints/edarxiv", zh: "教育学与教育研究预印本。", en: "Preprints for education research.", icon: "png" },
  { id: "philarchive", name: "PhilArchive", home: "https://philarchive.org/", zh: "哲学专业开放论文库。", en: "An open archive for philosophy.", icon: "png" },
];

export const TOOLS: Tool[] = [
  {
    id: "arxiv-abs",
    name: "arXiv Abstract",
    nameZh: "arXiv 摘要页",
    blurb: "Official page for the abstract, versions, authors, and DOI.",
    blurbZh: "官方页面看摘要、版本、作者与 DOI。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/abs/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 · title matches",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-pdf",
    name: "arXiv PDF",
    nameZh: "arXiv PDF",
    blurb: "The most stable route to the original PDF.",
    blurbZh: "最稳定的原版 PDF 入口。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/pdf/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 PDF",
    probeNoteZh: "200 PDF",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-html",
    name: "arXiv HTML",
    nameZh: "arXiv HTML",
    blurb: "Official searchable HTML with copyable text and formulas.",
    blurbZh: "官方网页正文，可搜索、复制和看公式。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/html/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200 HTML",
    probeNoteZh: "200 HTML",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-txt",
    name: "arXiv TXT",
    nameZh: "arXiv TXT",
    blurb: "Turn a paper into plain text an LLM can ingest.",
    blurbZh: "把论文变成 LLM 能直接吃的纯文本。",
    category: "agent",
    kind: "paper",
    url: "https://www.arxiv-txt.org/abs/{id}",
    home: "https://www.arxiv-txt.org/",
    probe: "hub-only",
    probeNote: "Paste an arXiv ID on the public site",
    probeNoteZh: "在公开网站粘贴 arXiv ID",
    langs: ["en"],
  },
  {
    id: "arxiv2md",
    name: "arXiv2MD",
    nameZh: "arXiv2MD",
    blurb: "Clean paper HTML into LLM-friendly Markdown.",
    blurbZh: "把 HTML 清成适合 LLM 的 Markdown。",
    category: "agent",
    kind: "hub",
    url: "https://www.arxiv2md.org/",
    home: "https://www.arxiv2md.org/",
    icon: "icons/arxiv2md.ico",
    probe: "hub-only",
    probeNote: "Paste an arXiv ID on the public site",
    probeNoteZh: "在公开网站粘贴 arXiv ID",
    langs: ["en"],
  },
  {
    id: "arxiv-src",
    name: "arXiv Source",
    nameZh: "arXiv 源码包",
    blurb: "Download TeX, BibTeX, and figure sources.",
    blurbZh: "下载 TeX、Bib 和图片源文件。",
    category: "source",
    kind: "paper",
    url: "https://arxiv.org/src/{id}",
    home: "https://arxiv.org/",
    probe: "verified",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "alphaxiv",
    name: "alphaXiv",
    nameZh: "alphaXiv",
    blurb: "Ask while you read, with community notes beside the paper.",
    blurbZh: "边读论文边提问，旁边还有社区注释。",
    category: "ai-chat",
    kind: "paper",
    url: "https://www.alphaxiv.org/abs/{id}",
    home: "https://www.alphaxiv.org/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need | alphaXiv",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "papers-cool",
    name: "Papers.cool",
    nameZh: "Cool Papers",
    blurb: "Browse fresh arXiv by category, with Kimi one click away.",
    blurbZh: "按 arXiv 分类刷新论文，Kimi 入口就在旁边。",
    category: "ai-summary",
    kind: "paper",
    url: "https://papers.cool/arxiv/{id}",
    home: "https://papers.cool/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need | Cool Papers",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["zh", "en"],
  },
  {
    id: "hjfy",
    name: "HJFY",
    nameZh: "幻觉翻译",
    blurb: "Generate a Chinese PDF that keeps the original layout.",
    blurbZh: "生成接近原排版的中文 PDF。",
    category: "translate",
    kind: "paper",
    url: "https://hjfy.top/arxiv/{id}",
    home: "https://hjfy.top/",
    probe: "verified",
    probeNote: "200 SPA; live pages render 幻觉翻译 for this id",
    probeNoteZh: "200，该 ID 可打开中文译文",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "chinarxiv",
    name: "ChinArXiv",
    nameZh: "ChinArXiv 翻译",
    blurb: "Open a bilingual version for side-by-side reading.",
    blurbZh: "打开中英双语版本，适合对照读。",
    category: "translate",
    kind: "hub",
    url: "https://chinarxiv.chatpaper.top/",
    home: "https://chinarxiv.chatpaper.top/",
    probe: "hub-only",
    probeNote: "Home 200. /arxiv/{id} → 404. Paste ID in the form.",
    probeNoteZh: "首页 200；/arxiv/{id} 为 404，需在表单粘贴 ID",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "chatpaper",
    name: "ChatPaper",
    nameZh: "ChatPaper",
    blurb: "Chat with the paper while browsing a daily paper feed.",
    blurbZh: "围绕论文正文对话，顺便刷每日论文。",
    category: "ai-chat",
    kind: "hub",
    url: "https://chatpaper.com/",
    home: "https://chatpaper.com/",
    icon: "icons/chatpaper.png",
    probe: "hub-only",
    probeNote: "200. ?arxiv={id} still serves the homepage.",
    probeNoteZh: "200；带 arxiv 参数仍是首页",
    langs: ["zh", "en"],
  },
  {
    id: "iarxiv",
    name: "IArxiv",
    nameZh: "IArxiv",
    blurb: "Discover arXiv by interest; sign in for personalization.",
    blurbZh: "按个人兴趣发现 arXiv，登录后更懂你。",
    category: "discover",
    kind: "hub",
    url: "https://iarxiv.org/",
    home: "https://iarxiv.org/",
    icon: "icons/iarxiv.ico",
    probe: "hub-only",
    probeNote: "Homepage requires sign-in.",
    probeNoteZh: "首页需登录。",
    langs: ["en"],
  },
  {
    id: "arxivdaily",
    name: "ArXiv Daily",
    nameZh: "ArXiv Daily",
    blurb: "Daily arXiv picks with Chinese summaries.",
    blurbZh: "每天整理新论文，还给中文摘要。",
    category: "discover",
    kind: "hub",
    url: "https://www.arxivdaily.com/",
    home: "https://www.arxivdaily.com/",
    probe: "hub-only",
    probeNote: "Home 200. /paper/{id} → 404.",
    probeNoteZh: "首页 200；/paper/{id} 为 404",
    featured: true,
    langs: ["zh"],
  },
  {
    id: "paperdance",
    name: "PaperDance",
    nameZh: "PaperDance",
    blurb: "Turn new papers into easy-to-scan visual cards.",
    blurbZh: "把新论文做成图文卡片，刷起来不累。",
    category: "discover",
    kind: "hub",
    url: "https://paperdance.org/",
    home: "https://paperdance.org/",
    probe: "hub-only",
    probeNote: "/abs/{id} returns the same SPA shell. Feed, not a paper page.",
    probeNoteZh: "/abs/{id} 与首页同一套 SPA，无单篇页",
    featured: true,
    langs: ["zh", "en"],
  },
  {
    id: "arxivtldr",
    name: "ArXiv TLDR",
    nameZh: "ArXiv TLDR",
    blurb: "Compress a paper into TLDR, key points, and why it matters.",
    blurbZh: "一页压缩 TLDR、关键要点和 Why it matters。",
    category: "ai-summary",
    kind: "paper",
    url: "https://arxivtldr.org/abs/{id}",
    home: "https://arxivtldr.org/",
    probe: "verified",
    probeNote: "200 · TL;DR: Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxivxplorer",
    name: "ArXiv Xplorer",
    nameZh: "ArXiv Xplorer",
    blurb: "Search arXiv semantically with text, IDs, or URLs.",
    blurbZh: "用自然语言、ID 或 URL 做 arXiv 语义搜索。",
    category: "search",
    kind: "search",
    url: "https://arxivxplorer.com/?q={id}",
    home: "https://arxivxplorer.com/",
    probe: "reachable",
    probeNote: "Home 200. /abs/{id} and /paper/{id} → 404. ?q= works.",
    probeNoteZh: "首页 200；/abs 与 /paper 404；?q= 可用",
    featured: true,
    langs: ["en"],
  },
  {
    id: "arxiv-bshk",
    name: "arXiv BSHK",
    nameZh: "arXiv BSHK 语义搜索",
    blurb: "A lightweight semantic search when keywords fall short.",
    blurbZh: "轻量语义搜索，关键词不够时来这里。",
    category: "search",
    kind: "hub",
    url: "https://arxiv.bshk.app/",
    home: "https://arxiv.bshk.app/",
    probe: "hub-only",
    probeNote: "SPA 200. /abs/{id} is the same shell, not a paper page.",
    probeNoteZh: "SPA 首页；/abs/{id} 不是论文页",
    featured: true,
    langs: ["en"],
  },
  {
    id: "scirate",
    name: "SciRate",
    nameZh: "SciRate",
    blurb: "Use researcher votes and comments to cut through noise.",
    blurbZh: "看研究者投票和评论，筛掉信息噪声。",
    category: "discussion",
    kind: "paper",
    url: "https://scirate.com/arxiv/{id}",
    home: "https://scirate.com/",
    probe: "cf",
    probeNote: "Canonical /arxiv/{id}. Datacenter hit Cloudflare.",
    probeNoteZh: "标准深链 /arxiv/{id}；机房 IP 遇 Cloudflare",
    featured: true,
    langs: ["en"],
  },
  {
    id: "pith",
    name: "Pith",
    nameZh: "Pith",
    blurb: "Public machine reviews that call out major issues and weak arguments.",
    blurbZh: "公开机器审稿，直接指出主要问题和可疑论证。",
    category: "discussion",
    kind: "paper",
    url: "https://pith.science/paper/{id}",
    home: "https://pith.science/",
    icon: "icons/pith.svg",
    probe: "verified",
    probeNote: "200 · JTA title matches at /paper/2608.05594.",
    probeNoteZh: "200，论文讨论页标题与 2608.05594 匹配。",
    langs: ["en"],
  },
  {
    id: "arxivisual",
    name: "arXivisual",
    nameZh: "arXivisual",
    blurb: "Turn a complex method into a visual walkthrough.",
    blurbZh: "把方法流程做成视频，复杂结构一眼看懂。",
    category: "ai-summary",
    kind: "paper",
    url: "https://arxivisual.org/abs/{id}",
    home: "https://arxivisual.org/",
    probe: "verified",
    probeNote: "200 · Attention Is All You Need · arXivisual",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "hf-papers",
    name: "Hugging Face Papers",
    nameZh: "Hugging Face Papers",
    blurb: "Connect papers to models, datasets, demos, and community.",
    blurbZh: "把论文、模型、数据集、Demo 和社区串起来。",
    category: "search",
    kind: "paper",
    url: "https://huggingface.co/papers/{id}",
    home: "https://huggingface.co/papers",
    icon: "icons/hf-papers.ico",
    probe: "verified",
    probeNote: "200 · Paper page - Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    featured: true,
    langs: ["en"],
  },
  {
    id: "ar5iv",
    name: "ar5iv",
    nameZh: "ar5iv HTML",
    blurb: "Turn TeX into browser-friendly HTML.",
    blurbZh: "把 TeX 变成更适合网页阅读的 HTML。",
    category: "source",
    kind: "paper",
    url: "https://ar5iv.labs.arxiv.org/html/{id}",
    home: "https://ar5iv.labs.arxiv.org/",
    probe: "verified",
    probeNote: "200 · [1706.03762] Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    langs: ["en"],
  },
  {
    id: "emergent-mind",
    name: "Emergent Mind",
    nameZh: "Emergent Mind",
    blurb: "Track hot AI papers, topic pages, and research trends.",
    blurbZh: "追热门 AI 论文、主题页和研究趋势。",
    category: "discover",
    kind: "paper",
    url: "https://www.emergentmind.com/papers/{id}",
    home: "https://www.emergentmind.com/",
    probe: "verified",
    probeNote: "200 · Transformer: Attention Is All You Need",
    probeNoteZh: "200，标题命中",
    langs: ["en"],
  },
  {
    id: "talk2arxiv",
    name: "Talk2Arxiv",
    nameZh: "Talk2Arxiv",
    blurb: "Change the URL and start chatting with an arXiv paper.",
    blurbZh: "改个链接就能和这篇 arXiv 论文对话。",
    category: "ai-chat",
    kind: "paper",
    url: "https://www.talk2arxiv.org/abs/{id}",
    home: "https://www.talk2arxiv.org/",
    probe: "reachable",
    probeNote: "200 Talk2Arxiv (generic title)",
    probeNoteZh: "200，通用标题",
    langs: ["en"],
  },
  {
    id: "gist-science",
    name: "Gist Science",
    nameZh: "Gist Science",
    blurb: "Get a plain explanation, conclusions, and a technical gist.",
    blurbZh: "通俗解释、核心结论和技术摘要一次给齐。",
    category: "ai-summary",
    kind: "paper",
    url: "https://gist.science/zh/paper/{id}",
    home: "https://gist.science/",
    icon: "icons/gist-science.svg",
    probe: "reachable",
    probeNote: "200 · Chinese paper explanation at /zh/paper/2608.05594.",
    probeNoteZh: "200，中文论文解读页可访问。",
    langs: ["en", "zh"],
  },
  {
    id: "moonlight",
    name: "Moonlight",
    nameZh: "Moonlight",
    blurb: "Read a review-style breakdown of methods, results, and impact.",
    blurbZh: "像读 Review 一样看方法、贡献、实验和意义。",
    category: "ai-summary",
    kind: "paper",
    url: "https://www.themoonlight.io/zh/review/{titleSlug}",
    home: "https://www.themoonlight.io/zh",
    icon: "icons/moonlight.ico",
    probe: "reachable",
    probeNote: "Title-derived slug, not an official arXiv ID route; missing titles open Explore. Review probe rate-limited (429).",
    probeNoteZh: "按标题生成链接，非官方 arXiv ID 直达；缺少标题时打开 Explore。论文页探测遇到限流（429）。",
    langs: ["en", "zh"],
  },
  {
    id: "growbotics",
    name: "Growbotics",
    nameZh: "Growbotics",
    blurb: "Robotics and embodied-AI papers with project context.",
    blurbZh: "机器人和具身智能论文的重点与项目资源。",
    category: "ai-summary",
    kind: "hub",
    url: "https://robotics.growbotics.ai/research/papers",
    home: "https://robotics.growbotics.ai/research/papers",
    icon: "icons/growbotics.svg",
    probe: "hub-only",
    probeNote: "Browse or search the site's paper directory.",
    probeNoteZh: "打开论文目录，由用户自行搜索。",
    langs: ["en"],
  },
  {
    id: "deeppaper",
    name: "DeepPaper",
    nameZh: "DeepPaper",
    blurb: "Browse papers by field and topic without getting lost.",
    blurbZh: "按领域和主题整理论文，不用在 arXiv 里迷路。",
    category: "ai-summary",
    kind: "paper",
    url: "https://arxiv.deeppaper.ai/papers/{id}",
    home: "https://arxiv.deeppaper.ai/",
    icon: "icons/deeppaper.svg",
    probe: "verified",
    probeNote: "200 · JTA title matches with both /papers/2608.05594 and /papers/2608.05594v1.",
    probeNoteZh: "200，带版本号或无版本号均可打开对应论文。",
    langs: ["en", "zh"],
  },
  {
    id: "aipapers",
    name: "AI Papers",
    nameZh: "AI Papers",
    blurb: "Daily AI picks with semantic paper Q&A.",
    blurbZh: "每日精选 AI 论文，顺手做语义问答。",
    category: "discover",
    kind: "search",
    url: "https://aipapers.ai/search?search={titleEnc}",
    home: "https://aipapers.ai/",
    probe: "cf",
    probeNote: "Title search query preserved; Cloudflare 403 in automated browser, results unverified.",
    probeNoteZh: "标题检索参数保留；自动浏览器遇 Cloudflare 403，结果未核验。",
    langs: ["en"],
  },
  {
    id: "aimodels-fyi",
    name: "AIModels.fyi",
    nameZh: "AIModels.fyi",
    blurb: "Question-style summaries connected to the model ecosystem.",
    blurbZh: "用问题式摘要连接 AI 论文与模型生态。",
    category: "ai-summary",
    kind: "search",
    url: "https://www.aimodels.fyi/papers?search={id}&selectedTimeRange=allTime&page=",
    home: "https://www.aimodels.fyi/",
    icon: "icons/aimodels-fyi.png",
    probe: "cf",
    probeNote: "ID search and allTime filter preserved; Vercel Security Checkpoint 403, results unverified.",
    probeNoteZh: "ID 与全部时间筛选参数保留；遇 Vercel 403 安全验证，结果未核验。",
    langs: ["en"],
  },
  {
    id: "sciencecast",
    name: "ScienceCast",
    nameZh: "ScienceCast",
    blurb: "The presentation version of a paper, in video and interactive media.",
    blurbZh: "论文的演讲版：视频和交互媒体一起讲。",
    category: "ai-summary",
    kind: "hub",
    url: "https://www.sciencecast.org/",
    home: "https://www.sciencecast.org/",
    icon: "icons/sciencecast.webp",
    probe: "hub-only",
    probeNote: "Research video platform homepage.",
    probeNoteZh: "科研视频平台首页。",
    langs: ["en"],
  },
  {
    id: "opentrain", name: "OpenTrain AI", nameZh: "OpenTrain AI",
    blurb: "Find implementations with maintenance, CI, and license signals.",
    blurbZh: "按 ID 找实现，并查看维护、CI 和许可证信号。",
    category: "search", kind: "paper",
    url: "https://www.opentrain.ai/papers/arxiv-{id}", home: "https://www.opentrain.ai/papers/",
    icon: "icons/opentrain.png", probe: "verified",
    probeNote: "The arXiv ID route redirects to the matching paper page.",
    probeNoteZh: "arXiv ID 入口自动跳转到对应论文页。",
    langs: ["en"],
  },
  {
    id: "paperlayer", name: "Paperlayer", nameZh: "Paperlayer",
    blurb: "AI summaries point back to evidence in the paper.",
    blurbZh: "AI 总结能回指原文证据，少一点黑箱感。",
    category: "ai-summary", kind: "paper",
    url: "https://paperlayer.ai/abs/{id}/zh", home: "https://paperlayer.ai/",
    icon: "icons/paperlayer.svg", probe: "verified",
    probeNote: "The versionless ID redirects to the matching Chinese paper page.",
    probeNoteZh: "按 arXiv ID 打开对应版本的中文论文页。",
    langs: ["en", "zh"],
  },
  {
    id: "arcxiv", name: "ArcXiv", nameZh: "ArcXiv",
    blurb: "Connect search APIs, structured Markdown, and MCP.",
    blurbZh: "搜索 API、结构化 Markdown 和 MCP 一起接入。",
    category: "agent", kind: "hub",
    url: "https://arcxiv.org/", home: "https://arcxiv.org/",
    icon: "icons/arcxiv.svg", probe: "hub-only",
    probeNote: "Public paper discovery homepage is reachable.", probeNoteZh: "论文发现首页可访问。",
    langs: ["en"],
  },
  {
    id: "sciencestack", name: "ScienceStack", nameZh: "ScienceStack",
    blurb: "Break abstracts, sections, equations, and figures into structure.",
    blurbZh: "把摘要、章节、公式和图表拆成可读结构。",
    category: "ai-summary", kind: "paper",
    url: "https://www.sciencestack.ai/paper/{id}", home: "https://www.sciencestack.ai/",
    icon: "icons/sciencestack.png", probe: "verified", probeNote: "Paper title and abstract matched; content depends on availability.",
    probeNoteZh: "已核对论文题名与摘要；全文内容以站点收录为准。", langs: ["en"],
  },
  {
    id: "summarizepaper", name: "SummarizePaper", nameZh: "SummarizePaper",
    blurb: "Generate key points and a plain summary before you commit.",
    blurbZh: "按 ID 生成关键点和通俗摘要，先扫一眼再决定。",
    category: "ai-summary", kind: "paper",
    url: "https://www.summarizepaper.com/en/arxiv-id/{id}", home: "https://www.summarizepaper.com/",
    icon: "icons/summarizepaper.ico", probe: "verified", probeNote: "The ID route resolves to a version with matching paper metadata.",
    probeNoteZh: "按 ID 跳转到对应版本，已核对题名与摘要。", langs: ["en"],
  },
  {
    id: "scholarfeed", name: "Scholar Feed", nameZh: "Scholar Feed",
    blurb: "Filter papers by relevance, novelty, and impact.",
    blurbZh: "按相关性、新颖性和影响力筛论文。",
    category: "discover", kind: "paper",
    url: "https://www.scholarfeed.org/paper/{id}", home: "https://www.scholarfeed.org/",
    icon: "icons/scholarfeed.svg", probe: "cf", probeNote: "A paper page matched; some requests encounter Cloudflare protection.",
    probeNoteZh: "已核对论文页内容；部分请求会遇到 Cloudflare 验证。", langs: ["en"],
  },
  {
    id: "arxivmax", name: "arXivMax", nameZh: "arXivMax",
    blurb: "Turn a paper into an explainer and video overview.",
    blurbZh: "把论文变成 Explainer 和视频，快速抓住全貌。",
    category: "ai-summary", kind: "paper",
    url: "https://www.arxivmax.com/papers/{id}", home: "https://www.arxivmax.com/",
    icon: "icons/arxivmax.svg", probe: "verified", probeNote: "Paper metadata matched; explanations may require generation.",
    probeNoteZh: "论文信息已核对；部分论文尚未生成讲解。", langs: ["en"],
  },
  {
    id: "arxivlens", name: "ArxivLens", nameZh: "ArxivLens",
    blurb: "Get quick summaries, key findings, and citation context.",
    blurbZh: "跨论文库给出 Quick Summary、Key Findings 和引用。",
    category: "ai-summary", kind: "search",
    url: "https://arxivlens.com/search?query=&doiOrArxivId={id}", home: "https://arxivlens.com/",
    icon: "icons/arxivlens.svg", probe: "reachable", probeNote: "Use the dedicated DOI/arXiv ID search parameter.",
    probeNoteZh: "使用独立的 DOI / arXiv ID 参数检索。", langs: ["en"],
  },
  {
    id: "searchthearxiv", name: "searchthearXiv", nameZh: "searchthearXiv",
    blurb: "Start from one paper and find nearby research.",
    blurbZh: "围绕一篇论文继续找相近研究。",
    category: "search", kind: "search",
    url: "https://searchthearxiv.com/?q=arXiv%3A{id}&tab=papers", home: "https://searchthearxiv.com/",
    icon: "icons/searchthearxiv.png", probe: "reachable", probeNote: "Search with an arXiv-prefixed ID in the papers tab.",
    probeNoteZh: "以 arXiv 前缀的 ID 检索并打开论文结果标签。", langs: ["en"],
  },
  {
    id: "astro-arxiv-sanity", name: "Astro arXiv Sanity", nameZh: "Astro arXiv Sanity",
    blurb: "An arXiv filter built for astrophysics.",
    blurbZh: "天体物理专用的论文筛选器。",
    category: "discover", kind: "hub", url: "https://astro-arxiv-sanity.com/", home: "https://astro-arxiv-sanity.com/",
    icon: "icons/astro-arxiv-sanity.png", probe: "hub-only", probeNote: "Astrophysics discovery homepage; personalized recommendations require an account.",
    probeNoteZh: "天体物理论文发现首页；个性化推荐需登录。", langs: ["en"],
  },
  {
    id: "arxivsub", name: "arXivSub", nameZh: "arXivSub",
    blurb: "Subscribe by author, institution, or keyword.",
    blurbZh: "按作者、机构和关键词订阅新论文。",
    category: "subscribe", kind: "hub", url: "https://arxivsub.comfyai.app/", home: "https://arxivsub.comfyai.app/",
    icon: "icons/arxivsub.ico", probe: "hub-only", probeNote: "Paper subscription and research digest homepage.",
    probeNoteZh: "论文订阅与研究简报首页。",
  },
  {
    id: "paperdigest", name: "Paper Digest", nameZh: "Paper Digest",
    blurb: "Track daily highlights by field and author.",
    blurbZh: "按领域和作者追踪每日论文 Highlight。",
    category: "subscribe", kind: "hub", url: "https://www.paperdigest.org/arxiv/", home: "https://www.paperdigest.org/arxiv/",
    icon: "icons/paperdigest.ico", probe: "hub-only", probeNote: "Public arXiv digest section, separate from paid research features.",
    probeNoteZh: "arXiv 公开摘要专区，高级研究服务可能另收费。", langs: ["en"],
  },
  {
    id: "arxivtok", name: "ArXivTok", nameZh: "ArXivTok",
    blurb: "Swipe through arXiv like short videos.",
    blurbZh: "TikTok 式刷 arXiv，低成本快速筛选。",
    category: "discover", kind: "hub", url: "https://arxivtok.vercel.app/", home: "https://arxivtok.vercel.app/",
    icon: "icons/arxivtok.png", probe: "hub-only", probeNote: "Public feed interface; the latest check showed No papers found.",
    probeNoteZh: "公开论文浏览入口；本次核验时显示暂无论文。", langs: ["en"],
  },
  {
    id: "latexml", name: "ar5iv Editor", nameZh: "ar5iv Editor",
    blurb: "Edit LaTeX in a browser with live HTML/MathML preview.",
    blurbZh: "浏览器里编辑 LaTeX，实时看 HTML/MathML。",
    category: "tool", kind: "hub", url: "https://latexml.rs/editor", home: "https://latexml.rs/editor",
    icon: "icons/latexml.ico", probe: "hub-only", probeNote: "Official ar5iv Editor interface and documentation.",
    probeNoteZh: "ar5iv Editor 官方编辑器与说明入口。", langs: ["en"],
  },
  {
    id: "benty-fields", name: "Benty Fields", nameZh: "Benty Fields",
    blurb: "Papers, journal clubs, and seminars in one place.", blurbZh: "论文发现、Journal Club 和 Seminar 放一处。",
    category: "discover", kind: "hub",
    url: "https://www.benty-fields.com/seminars", home: "https://www.benty-fields.com/seminars",
    icon: "icons/benty-fields.png", probe: "hub-only", probeNote: "Public seminar directory.", probeNoteZh: "学术研讨会目录入口。", langs: ["en"],
  },
  {
    id: "ggrxiv", name: "ggrxiv", nameZh: "ggrxiv",
    blurb: "Discover daily preprints tailored to your research interests.", blurbZh: "按研究兴趣发现每日预印本。",
    category: "subscribe", kind: "hub", url: "https://www.ggrxiv.com/", home: "https://www.ggrxiv.com/",
    icon: "icons/ggrxiv.png", probe: "hub-only", probeNote: "Personalized preprint discovery homepage.", probeNoteZh: "个性化预印本发现首页。", langs: ["en"],
  },
  {
    id: "litdigest", name: "LitDigest", nameZh: "LitDigest",
    blurb: "Describe your interest and get a weekly matching digest.", blurbZh: "用一句研究方向换来每周匹配论文。",
    category: "subscribe", kind: "hub", url: "https://litdigest.app/", home: "https://litdigest.app/",
    icon: "icons/litdigest.svg", probe: "hub-only", probeNote: "Weekly research digest homepage.", probeNoteZh: "每周论文简报首页。", langs: ["en"],
  },
  {
    id: "inveni", name: "inveni", nameZh: "inveni",
    blurb: "Learn your interests from your library and recommend daily papers.", blurbZh: "从你的文献库学兴趣，每天推新论文。",
    category: "subscribe", kind: "hub", url: "https://inveni.uk/", home: "https://inveni.uk/",
    icon: "icons/inveni.png", probe: "hub-only", probeNote: "Early-access research discovery service.", probeNoteZh: "个性化研究发现服务，部分功能需邀请。", langs: ["en"],
  },
  {
    id: "paperswipe", name: "PaperSwipe", nameZh: "PaperSwipe",
    blurb: "Swipe through papers and keep the ones worth reading.", blurbZh: "像刷卡片一样筛论文，喜欢再留下。",
    category: "discover", kind: "hub", url: "https://paperswipe.co/", home: "https://paperswipe.co/",
    icon: "icons/paperswipe.png", probe: "hub-only", probeNote: "Paper discovery homepage with a public deck preview.", probeNoteZh: "论文发现首页提供公开卡片预览。", langs: ["en"],
  },
  {
    id: "sota-papers", name: "SOTA Papers", nameZh: "SOTA Papers",
    blurb: "Curated papers with short takes on strengths and contributions.", blurbZh: "编辑精选论文，用短文讲清贡献和强弱。",
    category: "discover", kind: "hub", url: "https://www.sotapapers.com/", home: "https://www.sotapapers.com/",
    icon: "icons/sota-papers.svg", probe: "hub-only", probeNote: "Curated research discovery homepage.", probeNoteZh: "精选研究发现首页。", langs: ["en"],
  },
  {
    id: "uncited", name: "Uncited", nameZh: "Uncited",
    blurb: "Track new papers across arXiv, bioRxiv, and journals.", blurbZh: "跨 arXiv、bioRxiv 和期刊追新文章。",
    category: "subscribe", kind: "hub", url: "https://uncited.org/", home: "https://uncited.org/",
    icon: "icons/uncited.svg", probe: "hub-only", probeNote: "Research feeds and paper tracking homepage.", probeNoteZh: "论文动态与研究追踪首页。", langs: ["en"],
  },
  {
    id: "weekinpapers", name: "WeekInPapers", nameZh: "WeekInPapers",
    blurb: "Weekly CS arXiv papers with plain summaries and applications.", blurbZh: "每周 CS arXiv 论文配通俗摘要和应用方向。",
    category: "discover", kind: "paper", url: "https://weekinpapers.com/paper/{id}", home: "https://weekinpapers.com/",
    icon: "icons/weekinpapers.svg", probe: "reachable", probeNote: "ID route for indexed papers; missing entries return 404.",
    probeNoteZh: "按 ID 打开已收录论文；未收录的条目返回 404。", langs: ["en"],
  },
  {
    id: "the-latest-in-ai", name: "The Latest in AI", nameZh: "The Latest in AI",
    blurb: "Cluster the latest AI papers and spot research trends.", blurbZh: "把最新 AI 论文聚成主题，看研究风向。",
    category: "discover", kind: "paper", url: "https://thelatestinai.com/papers/{id}", home: "https://thelatestinai.com/",
    icon: "icons/the-latest-in-ai.svg", probe: "reachable", probeNote: "Paper ID route; coverage is limited to indexed papers.",
    probeNoteZh: "按论文 ID 打开详情，以站点收录范围为准。", langs: ["en"],
  },
  {
    id: "asxiv", name: "asXiv", nameZh: "asXiv",
    blurb: "Ask the current paper questions from a lightweight reader.", blurbZh: "右侧直接追问当前论文，轻量但很顺手。",
    category: "ai-chat", kind: "paper", url: "https://asxiv.org/pdf/{id}", home: "https://asxiv.org/",
    icon: "icons/asxiv.ico", probe: "reachable", probeNote: "Paper information is visible; PDF and chat availability may vary.",
    probeNoteZh: "可查看论文信息；PDF 与问答功能以页面实际状态为准。", langs: ["en"],
  },
  {
    id: "catalyzex", name: "CatalyzeX", nameZh: "CatalyzeX",
    blurb: "Paper to code, with a single-minded Paper → Code focus.",
    blurbZh: "论文到代码，专门找 Paper → Code。",
    category: "search", kind: "search",
    url: "https://www.catalyzex.com/paper/{titleSlug}/code", home: "https://www.catalyzex.com/",
    icon: "icons/catalyzex.jpg", probe: "cf",
    probeNote: "Title-slug match, not a stable arXiv ID link. Probe received HTTP 403.",
    probeNoteZh: "按标题 Slug 匹配代码页，非 arXiv ID 直达；当前探测返回 403。",
    langs: ["en"],
  },
  {
    id: "explainpaper",
    name: "Explainpaper",
    nameZh: "Explainpaper",
    blurb: "Highlight the hard sentence and explain just that part.",
    blurbZh: "选中难句，让 AI 专门解释这一个地方。",
    category: "ai-chat",
    kind: "hub",
    url: "https://www.explainpaper.com/",
    home: "https://www.explainpaper.com/",
    probe: "hub-only",
    probeNote: "200. Upload / open a PDF — no arXiv ID route.",
    probeNoteZh: "200；需上传 PDF，无 ID 路由",
    langs: ["en"],
  },
  {
    id: "scispace",
    name: "SciSpace",
    nameZh: "SciSpace",
    blurb: "A research-PDF Copilot for highlights and follow-up questions.",
    blurbZh: "科研 PDF Copilot，划词解释并继续追问。",
    category: "ai-chat",
    kind: "search",
    url: "https://typeset.io/search?q={id}",
    home: "https://scispace.com/",
    probe: "reachable",
    probeNote: "Search URL 200. Direct /papers/ slug not stable.",
    probeNoteZh: "搜索 URL 200；直接 slug 不稳定",
    langs: ["en"],
  },
  {
    id: "chatdoc",
    name: "ChatDOC",
    nameZh: "ChatDOC",
    blurb: "Answers carry document citations you can trace back.",
    blurbZh: "回答带原文引用，问完还能回到证据。",
    category: "ai-chat",
    kind: "hub",
    url: "https://chatdoc.com/",
    home: "https://chatdoc.com/",
    icon: "icons/chatdoc.ico",
    probe: "hub-only",
    probeNote: "Upload a document on the public site.",
    probeNoteZh: "在网站上传文档。",
    langs: ["en"],
  },
  {
    id: "consensus",
    name: "Consensus",
    nameZh: "Consensus",
    blurb: "Put a research question to evidence from multiple papers.",
    blurbZh: "把研究问题交给多篇论文一起回答。",
    category: "search",
    kind: "search",
    url: "https://consensus.app/search/?q={titleEnc}",
    home: "https://consensus.app/",
    probe: "cf",
    probeNote: "Home 200; search Cloudflare-walled here.",
    probeNoteZh: "首页 200；搜索遇墙",
    langs: ["en"],
  },
  {
    id: "litmaps",
    name: "Litmaps",
    nameZh: "Litmaps",
    blurb: "Grow a forward-and-backward citation map from one seed paper.",
    blurbZh: "从一篇种子论文画出前后继引用地图。",
    category: "search",
    kind: "hub",
    url: "https://app.litmaps.com/preview",
    home: "https://app.litmaps.com/preview",
    icon: "icons/litmaps.png",
    probe: "hub-only",
    probeNote: "Public preview page without a fixed paper identifier.",
    probeNoteZh: "公开预览页，不指定固定论文编号。",
    langs: ["en"],
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    nameZh: "Connected Papers",
    blurb: "See a co-citation map rather than a flat citation list.",
    blurbZh: "看共引关系图，不只是普通引用列表。",
    category: "search",
    kind: "paper",
    url: "https://www.connectedpapers.com/api/redirect/arxiv/{id}",
    home: "https://www.connectedpapers.com/",
    icon: "icons/connected-papers.ico",
    probe: "spa",
    probeNote: "Redirect to the paper using its arXiv ID.",
    probeNoteZh: "通过 arXiv ID 重定向到对应论文。",
    langs: ["en"],
  },
  {
    id: "inciteful",
    name: "Inciteful",
    nameZh: "Inciteful",
    blurb: "Expand citations in both directions and find bridge papers.",
    blurbZh: "展开前向和后向引用，找关键桥接文献。",
    category: "search",
    kind: "search",
    url: "https://inciteful.xyz/?id=arxiv:{id}",
    home: "https://inciteful.xyz/",
    probe: "spa",
    probeNote: "SPA 200 for ?id=arxiv:{id}",
    probeNoteZh: "SPA 200",
    langs: ["en"],
  },
  {
    id: "paperscape",
    name: "Paperscape",
    nameZh: "Paperscape",
    blurb: "Explore the whole arXiv as a zoomable map.",
    blurbZh: "把整个 arXiv 画成一张可以缩放的地图。",
    category: "search",
    kind: "hub",
    url: "https://paperscape.org/",
    home: "https://paperscape.org/",
    probe: "reachable",
    probeNote: "200 Paperscape",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "papermatch",
    name: "PaperMatch",
    nameZh: "PaperMatch",
    blurb: "Drop in one paper and find close neighbors.",
    blurbZh: "丢进一篇论文，快速找内容相近的工作。",
    category: "search",
    kind: "hub",
    url: "https://papermatch.me/",
    home: "https://papermatch.me/",
    icon: "icons/papermatch.ico",
    probe: "hub-only",
    probeNote: "200. /{id} is the same SPA homepage.",
    probeNoteZh: "200；/{id} 仍是首页 SPA",
    langs: ["en"],
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    nameZh: "Semantic Scholar",
    blurb: "Search, TLDRs, citation graphs, and related papers in one place.",
    blurbZh: "搜索、TLDR、引用网络和相关论文一站完成。",
    category: "search",
    kind: "search",
    url: "https://www.semanticscholar.org/search?q={titleEnc}",
    home: "https://www.semanticscholar.org/",
    icon: "icons/semantic-scholar.png",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "github",
    name: "GitHub Search",
    nameZh: "GitHub Search",
    blurb: "Use an arXiv ID to find the implementation repository.",
    blurbZh: "拿 arXiv ID 反查真正的代码仓库。",
    category: "search",
    kind: "search",
    url: "https://github.com/search?q={id}&type=repositories",
    home: "https://github.com/search",
    icon: "icons/github.ico",
    probe: "reachable",
    probeNote: "Repository search using the arXiv ID.",
    probeNoteZh: "按 arXiv ID 搜索仓库。",
    langs: ["en"],
  },
  {
    id: "openalex",
    name: "OpenAlex",
    nameZh: "OpenAlex",
    blurb: "An open graph for authors, institutions, topics, and citations.",
    blurbZh: "开放知识图谱，追作者、机构、主题和引用。",
    category: "search",
    kind: "search",
    url: "https://openalex.org/works?filter=default.search:{titleEnc}",
    home: "https://openalex.org/",
    icon: "icons/openalex.png",
    probe: "spa",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "google-scholar",
    name: "Google Scholar",
    nameZh: "Google Scholar",
    blurb: "Find citations, alternate versions, and published editions.",
    blurbZh: "查被引、不同版本和正式发表版，覆盖面很大。",
    category: "search",
    kind: "search",
    url: "https://scholar.google.com/scholar_lookup?arxiv_id={id}",
    home: "https://scholar.google.com/",
    icon: "icons/google-scholar.ico",
    probe: "verified",
    probeNote: "200 Google Scholar",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "pwc",
    name: "Papers with Code",
    nameZh: "Papers with Code",
    blurb: "Connect papers, code, datasets, and SOTA benchmarks.",
    blurbZh: "论文、代码、数据集和 SOTA 榜单连在一起。",
    category: "search",
    kind: "paper",
    url: "https://paperswithcode.co/paper/{id}",
    home: "https://paperswithcode.co/",
    icon: "icons/papers-with-code.png",
    probe: "spa",
    probeNote: "Paper route by arXiv ID.",
    probeNoteZh: "按 arXiv ID 打开论文页。",
    langs: ["en"],
  },
  {
    id: "scholar-inbox",
    name: "Scholar Inbox",
    nameZh: "Scholar Inbox",
    blurb: "Train a paper inbox with likes and skips.",
    blurbZh: "用点赞/踩训练你的论文推荐收件箱。",
    category: "subscribe",
    kind: "hub",
    url: "https://www.scholar-inbox.com/",
    home: "https://www.scholar-inbox.com/",
    probe: "spa",
    probeNote: "SPA 200 Scholar Inbox",
    probeNoteZh: "SPA 200",
    langs: ["en"],
  },
  {
    id: "dblp",
    name: "DBLP",
    nameZh: "DBLP",
    blurb: "Check computer-science venues, authors, and publication records.",
    blurbZh: "确认计算机论文的会议、期刊和作者记录。",
    category: "search",
    kind: "search",
    url: "https://dblp.org/search?q={id}",
    home: "https://dblp.org/",
    probe: "reachable",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "gotit",
    name: "GotIt",
    nameZh: "GotIt",
    blurb: "Annotate the paper and keep discussion next to the text.",
    blurbZh: "围绕正文做批注，讨论就贴在原文旁边。",
    category: "discussion",
    kind: "paper",
    url: "https://gotit.pub/view/{id}",
    home: "https://gotit.pub/",
    icon: "icons/gotit.png",
    probe: "spa",
    probeNote: "Paper route uses the arXiv ID.",
    probeNoteZh: "论文路由需要 arXiv ID。",
    langs: ["en"],
  },
  {
    id: "prereview",
    name: "PREreview",
    nameZh: "PREreview",
    blurb: "Write an open peer review for a preprint.",
    blurbZh: "给预印本做开放同行评审。",
    category: "discussion",
    kind: "paper",
    url: "https://prereview.org/preprints/doi-10.48550-arxiv.{id}/write-a-prereview",
    home: "https://prereview.org/",
    icon: "icons/prereview.svg",
    probe: "spa",
    probeNote: "Preprint review form using its arXiv DOI.",
    probeNoteZh: "使用 arXiv DOI 打开预印本评审表单。",
    langs: ["en"],
  },
  {
    id: "pubpeer",
    name: "PubPeer",
    nameZh: "PubPeer",
    blurb: "Check post-publication concerns, corrections, and replies.",
    blurbZh: "看发表后质疑、勘误和作者回应。",
    category: "discussion",
    kind: "search",
    url: "https://www.pubpeer.com/search?q={id}",
    home: "https://www.pubpeer.com/",
    icon: "icons/pubpeer.png",
    probe: "reachable",
    probeNote: "Search URL using the arXiv ID.",
    probeNoteZh: "按 arXiv ID 搜索。",
    langs: ["en"],
  },
  {
    id: "openreview",
    name: "OpenReview",
    nameZh: "OpenReview",
    blurb: "Read reviews, rebuttals, and scores where available.",
    blurbZh: "直接看 Review、Rebuttal 和评分。",
    category: "discussion",
    kind: "search",
    url: "https://openreview.net/search?term={titleEnc}",
    home: "https://openreview.net/",
    icon: "icons/openreview.png",
    probe: "reachable",
    probeNote: "200",
    probeNoteZh: "200",
    langs: ["en"],
  },
  {
    id: "immersive-translate",
    name: "Immersive Translate",
    nameZh: "沉浸式翻译",
    blurb: "Translate papers, PDFs, and the rest of the research web.",
    blurbZh: "网页和 PDF 一起翻，科研网页也能用。",
    category: "translate",
    kind: "hub",
    url: "https://app.immersivetranslate.com/babel-doc/",
    home: "https://app.immersivetranslate.com/babel-doc/",
    probe: "reachable",
    probeNote: "Public Babel Doc entry",
    probeNoteZh: "公开 Babel Doc 入口",
    langs: ["zh", "en"],
  },
  {
    id: "zotero-bib",
    name: "ZoteroBib",
    nameZh: "ZoteroBib",
    blurb: "Get BibTeX from a DOI or URL without installing Zotero.",
    blurbZh: "不用装 Zotero，输入 DOI/URL 就出 BibTeX。",
    category: "tool",
    kind: "hub",
    url: "https://zbib.org/",
    home: "https://zbib.org/",
    icon: "icons/zotero.ico",
    probe: "reachable",
    probeNote: "Public bibliography builder",
    probeNoteZh: "公开参考文献生成器",
    langs: ["en"],
  },
  {
    id: "pdf2zh", name: "PDF2zh", nameZh: "PDF2zh",
    blurb: "Keep PDF layout, equations, and figures intact.",
    blurbZh: "重点保留 PDF 的布局、公式和图表。",
    category: "translate", kind: "hub", url: "https://pdf2zh.com/", home: "https://pdf2zh.com/",
    icon: "icons/pdf2zh.svg", probe: "hub-only", probeNote: "Public PDF translation form; conversion itself was not tested.",
    probeNoteZh: "提供公开 PDF 翻译表单；本次未上传文档执行翻译。", langs: ["zh", "en"],
  },
  {
    id: "zotmeta",
    name: "ZotMeta",
    nameZh: "ZotMeta",
    blurb: "Repair metadata with DOI, ISBN, or arXiv ID.",
    blurbZh: "用 DOI、ISBN、arXiv ID 修元数据。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/RoadToDream/ZotMeta",
    home: "https://github.com/RoadToDream/ZotMeta",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotero-arxiv-workflow",
    name: "arXiv Workflow",
    nameZh: "arXiv Workflow",
    blurb: "Track publication updates and merge preprint versions.",
    blurbZh: "追踪正式发表，并合并预印本版本。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/AllanChain/zotero-arxiv-workflow",
    home: "https://github.com/AllanChain/zotero-arxiv-workflow",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "hjfy-split-reader",
    name: "HJFY Split Reader",
    nameZh: "HJFY Split Reader",
    blurb: "Read the original and translation side by side in Zotero.",
    blurbZh: "在 Zotero 里并排看原文和译文。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/Infinity4B/zotero-hjfy-split-reader",
    home: "https://github.com/Infinity4B/zotero-hjfy-split-reader",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["zh", "en"],
  },
  {
    id: "arxiv-marker",
    name: "arxiv-marker",
    nameZh: "arxiv-marker",
    blurb: "Add venues, CCF/CORE ranks, and citations to arXiv items.",
    blurbZh: "给 arXiv 条目补会议、CCF/CORE 和引用。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/lelelelelelelelelelelelele/arxiv-marker",
    home: "https://github.com/lelelelelelelelelelelelele/arxiv-marker",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotero-citation-tally",
    name: "Citation Tally",
    nameZh: "Citation Tally",
    blurb: "See multi-source citation counts in Zotero.",
    blurbZh: "在 Zotero 列表里直接看多源引用量。",
    category: "zotero",
    kind: "hub",
    url: "https://github.com/daeh/zotero-citation-tally",
    home: "https://github.com/daeh/zotero-citation-tally",
    probe: "reachable",
    probeNote: "GitHub plugin repository",
    probeNoteZh: "GitHub 插件仓库",
    langs: ["en"],
  },
  {
    id: "zotero-arxiv-daily", name: "Zotero-arXiv-Daily", nameZh: "Zotero-arXiv-Daily",
    blurb: "Recommend daily arXiv papers from your Zotero library.",
    blurbZh: "用你的 Zotero 文库每天推荐新 arXiv。",
    category: "zotero", kind: "hub",
    url: "https://github.com/TideDra/zotero-arxiv-daily", home: "https://github.com/TideDra/zotero-arxiv-daily",
    icon: "icons/github.ico", probe: "hub-only",
    probeNote: "Zotero-based recommendation workflow, not an XPI plugin.",
    probeNoteZh: "基于 Zotero 的论文推荐工作流，不是 XPI 插件。", langs: ["en", "zh"],
  },
  {
    id: "xiaohongshu",
    name: "Xiaohongshu",
    nameZh: "小红书搜索",
    blurb: "Find Chinese notes, diagrams, and reproduction tips.",
    blurbZh: "搜中文论文笔记、图解和复现经验。",
    category: "discussion",
    kind: "search",
    url: "https://www.xiaohongshu.com/search_result?keyword={titleEnc}",
    home: "https://www.xiaohongshu.com/",
    probe: "reachable",
    probeNote: "Title search URL",
    probeNoteZh: "论文标题搜索入口",
    langs: ["zh"],
  },
  {
    id: "x-search",
    name: "X Search",
    nameZh: "X 讨论搜索",
    blurb: "Follow author posts and real-time research threads.",
    blurbZh: "追作者发布和研究者即时讨论串。",
    category: "discussion",
    kind: "search",
    url: "https://x.com/search?q={titleEnc}",
    home: "https://x.com/",
    icon: "icons/x-search.png",
    probe: "reachable",
    probeNote: "Title search URL",
    probeNoteZh: "论文标题搜索入口",
    langs: ["en"],
  },
  {
    id: "reddit-search",
    name: "Reddit Search",
    nameZh: "Reddit 搜索",
    blurb: "Find longer, candid paper discussions in the community.",
    blurbZh: "找 AI 社区里更长、更敢说的讨论。",
    category: "discussion",
    kind: "search",
    url: "https://www.reddit.com/search/?q={titleEnc}",
    home: "https://www.reddit.com/",
    icon: "icons/reddit.png",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["en"],
  },
  {
    id: "zhihu-search",
    name: "Zhihu Search",
    nameZh: "知乎搜索",
    blurb: "Search Chinese explainers and technical context.",
    blurbZh: "搜索中文长文解读和技术背景。",
    category: "discussion",
    kind: "search",
    url: "https://www.zhihu.com/search?type=content&q={titleEnc}",
    home: "https://www.zhihu.com/",
    icon: "icons/zhihu.ico",
    probe: "reachable",
    probeNote: "Paper title search URL.",
    probeNoteZh: "论文标题搜索入口。",
    langs: ["zh"],
  },
];

TOOLS.push(
  {
    id: "markxiv", name: "MarkXiv", nameZh: "MarkXiv",
    blurb: "Generate Markdown from LaTeX structure.", blurbZh: "从 LaTeX 结构生成 Markdown。",
    category: "agent", kind: "hub", url: "https://markxiv.org/", home: "https://markxiv.org/",
    probe: "hub-only", probeNote: "Public tool", probeNoteZh: "公共工具入口",
  },
  {
    id: "arxiv-mcp", name: "arxiv-mcp", nameZh: "arxiv-mcp",
    blurb: "Search, download, and read arXiv by section through MCP.", blurbZh: "给 MCP 客户端搜索、下载和分章节读 arXiv。",
    category: "agent", kind: "hub", url: "https://github.com/blazickjp/arxiv-mcp-server", home: "https://github.com/blazickjp/arxiv-mcp-server",
    probe: "hub-only", probeNote: "MCP repository", probeNoteZh: "MCP 项目仓库",
  },
  {
    id: "arxiv-py", name: "arxiv.py", nameZh: "arxiv.py",
    blurb: "Search and download papers programmatically with Python.",
    blurbZh: "Python 分页搜索和下载论文。",
    category: "agent", kind: "hub",
    url: "https://github.com/lukasschwab/arxiv.py", home: "https://github.com/lukasschwab/arxiv.py",
    icon: "icons/github.ico", probe: "hub-only",
    probeNote: "Official Python API wrapper; a real paper lookup was verified.",
    probeNoteZh: "arXiv API 的 Python 封装，已实测单篇论文查询。", langs: ["en"],
  },
  {
    id: "scry", name: "Scry", nameZh: "Scry",
    blurb: "Bring arXiv, Reddit, and HN into an agent.",
    blurbZh: "把 arXiv、Reddit、HN 接进 Agent。",
    category: "agent", kind: "hub", url: "https://scry.io/", home: "https://scry.io/",
    icon: "icons/scry.ico", probe: "hub-only", probeNote: "Non-commercial free use depends on capacity; account and paid usage may apply.",
    probeNoteZh: "容量允许时可免费用于非商业用途，部分使用需账户或付费。", langs: ["en"],
  },
  {
    id: "easyread", name: "EasyRead", nameZh: "EasyRead",
    blurb: "A local bilingual reader for formulas, notes, and models.",
    blurbZh: "本地双语阅读器，公式、批注和模型都能接。",
    category: "tool", kind: "hub",
    url: "https://github.com/Edwardxlai/easyread", home: "https://github.com/Edwardxlai/easyread",
    icon: "icons/github.ico", probe: "hub-only",
    probeNote: "Official open-source workspace repository.", probeNoteZh: "开源论文阅读工作台官方仓库。", langs: ["zh", "en"],
  },
  {
    id: "alphaxiv-mcp", name: "alphaxiv-mcp", nameZh: "alphaxiv-mcp",
    blurb: "Let agents call alphaXiv full text and reports.", blurbZh: "让 Agent 调用 alphaXiv 的全文和报告。",
    category: "agent", kind: "hub", url: "https://www.alphaxiv.org/docs/mcp", home: "https://www.alphaxiv.org/docs/mcp",
    probe: "hub-only", probeNote: "MCP documentation", probeNoteZh: "MCP 接入文档",
  },
  {
    id: "deepxiv", name: "DeepXiv", nameZh: "DeepXiv",
    blurb: "A full-text research data layer for agents.", blurbZh: "给 Agent 用的科研全文数据层。",
    category: "agent", kind: "hub", url: "https://data.rag.ac.cn/", home: "https://data.rag.ac.cn/",
    icon: "icons/deepxiv.svg",
    probe: "hub-only", probeNote: "Research data portal", probeNoteZh: "科研数据平台",
  },
  {
    id: "arxiv-rss", name: "arxiv-rss", nameZh: "arxiv-rss 订阅生成",
    blurb: "Build a custom arXiv RSS feed from your own filters.", blurbZh: "自己拼条件，生成专属 arXiv RSS。",
    category: "subscribe", kind: "hub", url: "https://ronpay.github.io/arxiv-rss-feed-generator/", home: "https://ronpay.github.io/arxiv-rss-feed-generator/",
    probe: "hub-only", probeNote: "RSS generator", probeNoteZh: "RSS 订阅生成器",
  },
);

// 独立平台是公共入口，不构造当前 arXiv 论文的跨站深链。
TOOLS.push(...XIV_PLATFORMS.map((platform): Tool => ({
  id: platform.id,
  name: platform.name,
  nameZh: platform.name,
  blurb: platform.en,
  blurbZh: platform.zh,
  category: (platform.category ?? "xiv") as ToolCategory,
  kind: "hub",
  url: platform.home,
  home: platform.home,
  icon: `icons/xiv/${platform.id}.${platform.icon}`,
  probe: "hub-only",
  probeNote: "Independent preprint platform",
  probeNoteZh: "独立预印本平台",
})));

// 论文页顶栏的 Trackbacks 入口也作为原文类工具保留，方便目录和论文页使用同一套配置。
TOOLS.push({
  id: "arxiv-tb",
  name: "arXiv TB",
  nameZh: "arXiv TB",
  blurb: "Trace external trackbacks and links pointing to an arXiv paper.",
  blurbZh: "查看指向论文的外部 Trackbacks 与引用链接。",
  category: "source",
  kind: "paper",
  url: "https://arxiv.org/tb/{id}",
  home: "https://arxiv.org/tb/",
  probe: "hub-only",
  probeNote: "Official arXiv trackback page.",
  probeNoteZh: "arXiv 官方 Trackbacks 页面。",
  langs: ["en"],
});

export const PAPER_CATEGORIES = ["discussion", "ai-summary", "ai-chat", "search", "translate"] as const;

// 与首页使用相同的类别成员；公共工具保留其配置网址，不构造论文深链。
export const PAPER_TOOLS = TOOLS.filter((tool) => PAPER_CATEGORIES.some((category) =>
  tool.category === category || tool.additionalCategories?.includes(category),
));

export type ExtraLink = {
  paperId: string;
  name: string;
  nameZh: string;
  url: string;
  blurb: string;
  blurbZh: string;
};

export const EXTRAS: ExtraLink[] = [
  {
    paperId: "1706.03762",
    name: "The Annotated Transformer",
    nameZh: "The Annotated Transformer",
    url: "https://nlp.seas.harvard.edu/annotated-transformer/",
    blurb: "Harvard NLP line-by-line implementation of this paper.",
    blurbZh: "Harvard NLP 逐行实现。",
  },
  {
    paperId: "1706.03762",
    name: "The Illustrated Transformer",
    nameZh: "图解 Transformer",
    url: "https://jalammar.github.io/illustrated-transformer/",
    blurb: "Jay Alammar’s visual walkthrough.",
    blurbZh: "Jay Alammar 的图解。",
  },
  {
    paperId: "1706.03762",
    name: "NeurIPS 2017",
    nameZh: "NeurIPS 2017 正式版",
    url: "https://proceedings.neurips.cc/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
    blurb: "Conference proceedings page. Title verified.",
    blurbZh: "会议正式版，标题已核验。",
  },
];

export const EXAMPLE_PAPERS: Array<{
  id: string;
  title: string;
  year: string;
  href?: string;
}> = [
  { id: "1706.03762", title: "Attention Is All You Need", year: "2017" },
  { id: "2303.08774", title: "GPT-4", year: "2023" },
  { id: "2307.15818", title: "RT-2", year: "2023" },
  { id: "2504.16054", title: "Pi05", year: "2025" },
  { id: "2608.15875", title: "GigaBrain-0.7", year: "2026" },
];

export type ToolContext = {
  id: string;
  title?: string;
  doi?: string;
};

export function getGitHubRepository(href: string): string | null {
  try {
    const url = new URL(href);
    const parts = url.pathname.split("/").filter(Boolean);
    if (url.hostname !== "github.com" || parts.length !== 2) return null;
    return `${parts[0]}/${parts[1].replace(/\.git$/, "")}`;
  } catch {
    return null;
  }
}

export function countByProbe(status: ProbeStatus): number {
  return TOOLS.filter((t) => t.probe === status).length;
}
