import assert from 'node:assert/strict';
import test from 'node:test';
import { TOOLS, buildToolUrl } from '../src/lib/tools.ts';

const moonlight = TOOLS.find((tool) => tool.id === 'moonlight');

test('Moonlight title URLs match ordinary and mathematical title examples', () => {
  for (const [title, slug] of [
    ['Automated Radiology Report Generation: A Review of Recent Advances', 'automated-radiology-report-generation-a-review-of-recent-advances'],
    ['aiXiv: A Next-Generation Open Access Ecosystem for Scientific Discovery Generated by AI Scientists', 'aixiv-a-next-generation-open-access-ecosystem-for-scientific-discovery-generated-by-ai-scientists'],
    ['π₀.₅: a Vision-Language-Action Model with Open-World Generalization', '05-a-vision-language-action-model-with-open-world-generalization'],
    [String.raw`$\pi_{0.5}$: a Vision-Language-Action Model with Open-World Generalization`, '05-a-vision-language-action-model-with-open-world-generalization'],
    ['MT$^{3}$: Scaling MLLM-based Text Image Machine Translation via Multi-Task Reinforcement Learning', 'mt3-scaling-mllm-based-text-image-machine-translation-via-multi-task-reinforcement-learning'],
    ['  -- Café: A  Multi--Task Study! --  ', 'cafe-a-multi-task-study'],
  ]) {
    assert.equal(buildToolUrl(moonlight, { id: '2504.16054', title }), `https://www.themoonlight.io/zh/review/${slug}`);
  }
});

test('Moonlight uses Explore without a usable title, never an ID-derived slug', () => {
  for (const title of [undefined, '', '   ', '$\\pi$', '研究', '---']) {
    assert.equal(buildToolUrl(moonlight, { id: '2504.16054', title }), 'https://www.themoonlight.io/zh/explore');
  }
});

test('existing ID and title-search URL generation is preserved', () => {
  const ctx = { id: '2608.05594', title: 'Vision & Action' };
  assert.equal(buildToolUrl(TOOLS.find((tool) => tool.id === 'gist-science'), ctx), 'https://gist.science/zh/paper/2608.05594');
  assert.equal(buildToolUrl(TOOLS.find((tool) => tool.id === 'openreview'), ctx), 'https://openreview.net/search?term=Vision%20%26%20Action');
});

test('CatalyzeX code links follow title slug examples and fall back to search without a slug', () => {
  const tool = TOOLS.find((tool) => tool.id === 'catalyzex');
  for (const [title, slug] of [
    ['Attention Is All You Need', 'attention-is-all-you-need'],
    ['RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control', 'rt-2-vision-language-action-models-transfer'],
    ['OpenVLA: An Open-Source Vision-Language-Action Model', 'openvla-an-open-source-vision-language-action'],
    ['$π_0$: A Vision-Language-Action Flow Model for General Robot Control', '0-a-vision-language-action-flow-model-for'],
    [String.raw`$\pi_0$: A Vision-Language-Action Flow Model for General Robot Control`, '0-a-vision-language-action-flow-model-for'],
    ['GigaBrain-0.7: Scaling Embodied Foundation Models to Emergent Capabilities with a Three-System Architecture', 'gigabrain-0-7-scaling-embodied-foundation'],
  ]) assert.equal(buildToolUrl(tool, { id: '2608.15875', title }), `https://www.catalyzex.com/paper/${slug}/code`);
  assert.equal(buildToolUrl(tool, { id: '2608.15875' }), 'https://www.catalyzex.com/s/2608.15875');
  assert.equal(buildToolUrl(tool, { id: '2608.15875', title: '研究' }), `https://www.catalyzex.com/s/${encodeURIComponent('研究')}`);
});
