import assert from 'node:assert/strict';
import test from 'node:test';
import { TOOLS, buildToolUrl } from '../src/lib/tools.ts';

const moonlight = TOOLS.find((tool) => tool.id === 'moonlight');

test('Moonlight title URLs match ordinary and mathematical title examples', () => {
  for (const [title, slug] of [
    ['Automated Radiology Report Generation: A Review of Recent Advances', 'automated-radiology-report-generation-a-review-of-recent-advances'],
    ['aiXiv: A Next-Generation Open Access Ecosystem for Scientific Discovery Generated by AI Scientists', 'aixiv-a-next-generation-open-access-ecosystem-for-scientific-discovery-generated-by-ai-scientists'],
    ['π₀.₅: a Vision-Language-Action Model with Open-World Generalization', '05-a-vision-language-action-model-with-open-world-generalization'],
    [String.raw`$\pi_{0.5}$: a Vision-Language-Action Model with Open-World Generalization`, '05-a-vision-language-action-model-with-open-world-generalization'],
    ['MT$^{3}$: Scaling MLLM-based Text Image Machine Translation via Multi-Task Reinforcement Learning', 'mt3-scaling-mllm-based-text-image-machine-translation-via-multi-task-reinforcement-learning'],
    ['  -- Café: A  Multi--Task Study! --  ', 'cafe-a-multi-task-study'],
  ]) {
    assert.equal(buildToolUrl(moonlight, { id: '2504.16054', title }), `https://www.themoonlight.io/zh/review/${slug}`);
  }
});

test('Moonlight uses Explore without a usable title, never an ID-derived slug', () => {
  for (const title of [undefined, '', '   ', '$\\pi$', '研究', '---']) {
    assert.equal(buildToolUrl(moonlight, { id: '2504.16054', title }), 'https://www.themoonlight.io/zh/explore');
  }
});

test('existing ID and title-search URL generation is preserved', () => {
  const ctx = { id: '2608.05594', title: 'Vision & Action' };
  assert.equal(buildToolUrl(TOOLS.find((tool) => tool.id === 'gist-science'), ctx), 'https://gist.science/zh/paper/2608.05594');
  assert.equal(buildToolUrl(TOOLS.find((tool) => tool.id === 'openreview'), ctx), 'https://openreview.net/search?term=Vision%20%26%20Action');
});
